// Copyright 2026 Matthew Allen. Licensed under the Modified Apache License, Version 2.0.
import * as Icons from "./index";
import type { Component } from "svelte";

export type IconName =
  | "PlusIcon"
  | "MinusCircleIcon"
  | "CloseIcon"
  | "TrashIcon"
  | "PlayIcon"
  | "PauseIcon"
  | "ProtractorIcon"
  | "SaveIcon"
  | "DownloadIcon"
  | "MagnetIcon"
  | "FolderIcon"
  | "PuzzleIcon"
  | "ListIcon"
  | "ArrowRightIcon"
  | "CodeIcon"
  | "TerminalIcon"
  | "StarIcon"
  | "ZapIcon"
  | "WrenchIcon"
  | "EyeIcon"
  | "BoxIcon"
  | "CompassIcon"
  | "ArrowsPointingOutIcon"
  | "SwitchIcon"
  | "ScissorsIcon"
  | "Bars3Icon"
  | "ShowRobotIcon"
  | "ShowFakeHeadingArrowIcon"
  | "ValidateFieldBoundariesIcon"
  | "ContinuousValidationIcon"
  | "RestrictDraggingToFieldIcon"
  | "SmartSnappingIcon"
  | "FollowRobotIcon"
  | "ShowTelemetryTabIcon"
  | "PresentationModeIcon"
  | "ExportGifIcon"
  | "UndoIcon"
  | "RedoIcon"
  | "ClockIcon"
  | "RulerIcon"
  | "GridIcon"
  | "OnionSkinIcon"
  | "VelocityHeatmapIcon"
  | "FeedbackIcon"
  | "GithubIcon"
  | "PenIcon"
  | "ChevronLeftIcon"
  | "ChevronRightIcon"
  | "SuccessIcon"
  | "InfoIcon"
  | "WarningIcon"
  | "TriangleWarningIcon"
  | "ErrorIcon"
  | "RocketIcon"
  | "LinkIcon"
  | "EyeSlashIcon"
  | "UnlockIcon"
  | "ArrowCircleIcon"
  | "PathTabIcon"
  | "FieldTabIcon"
  | "TableTabIcon"
  | "StatsIcon"
  | "SearchIcon"
  | "ResetIcon"
  | "ChevronUpIcon"
  | "ChevronDownIcon"
  | "LockIcon"
  | "SpinnerIcon"
  | "SidebarLeftIcon"
  | "SidebarBottomIcon"
  | "SidebarHiddenIcon"
  | "ChevronRightSolidIcon"
  | "ValidIcon"
  | "ArrowDownIcon"
  | "CloudArrowDownIcon"
  | "DocumentPlusIcon"
  | "FolderPlusIcon"
  | "ArrowDownTrayIcon"
  | "CodeBracketSquareIcon"
  | "ServerStackIcon"
  | "MinusIcon"
  | "ResetZoomIcon"
  | "ExitPresentationModeIcon"
  | "ArrowUpIcon"
  | "ClipboardIcon"
  | "CheckIcon"
  | "CogIcon"
  | "PlusCircleIcon"
  | "MapPinIcon"
  | "DocumentIcon"
  | "PhotoIcon"
  | "SortNameIcon"
  | "ViewListIcon"
  | "ViewGridIcon"
  | "QuestionMarkIcon"
  | "EllipsisHorizontalIcon"
  | "SkipToStartIcon"
  | "SkipToEndIcon"
  | "OnionSkinCurrentPathIcon"
  | "SidebarCollapseIcon"
  | "MicrosoftStoreIcon"
  | "RobotPlaceholderIcon"
  | "CriticalIcon"
  | "DisabledIcon"
  | "EllipsisVerticalIcon"
  | "KeyboardIcon";

export const iconMap: Record<IconName, Component<any>> = {
  PlusIcon: Icons.PlusIcon,
  MinusCircleIcon: Icons.MinusCircleIcon,
  CloseIcon: Icons.CloseIcon,
  TrashIcon: Icons.TrashIcon,
  PlayIcon: Icons.PlayIcon,
  PauseIcon: Icons.PauseIcon,
  ProtractorIcon: Icons.ProtractorIcon,
  SaveIcon: Icons.SaveIcon,
  DownloadIcon: Icons.DownloadIcon,
  MagnetIcon: Icons.MagnetIcon,
  FolderIcon: Icons.FolderIcon,
  PuzzleIcon: Icons.PuzzleIcon,
  ListIcon: Icons.ListIcon,
  ArrowRightIcon: Icons.ArrowRightIcon,
  CodeIcon: Icons.CodeIcon,
  TerminalIcon: Icons.TerminalIcon,
  StarIcon: Icons.StarIcon,
  ZapIcon: Icons.ZapIcon,
  WrenchIcon: Icons.WrenchIcon,
  EyeIcon: Icons.EyeIcon,
  BoxIcon: Icons.BoxIcon,
  CompassIcon: Icons.CompassIcon,
  ArrowsPointingOutIcon: Icons.ArrowsPointingOutIcon,
  SwitchIcon: Icons.SwitchIcon,
  ScissorsIcon: Icons.ScissorsIcon,
  Bars3Icon: Icons.Bars3Icon,
  ShowRobotIcon: Icons.ShowRobotIcon,
  ShowFakeHeadingArrowIcon: Icons.ShowFakeHeadingArrowIcon,
  ValidateFieldBoundariesIcon: Icons.ValidateFieldBoundariesIcon,
  ContinuousValidationIcon: Icons.ContinuousValidationIcon,
  RestrictDraggingToFieldIcon: Icons.RestrictDraggingToFieldIcon,
  SmartSnappingIcon: Icons.SmartSnappingIcon,
  FollowRobotIcon: Icons.FollowRobotIcon,
  ShowTelemetryTabIcon: Icons.ShowTelemetryTabIcon,
  PresentationModeIcon: Icons.PresentationModeIcon,
  ExportGifIcon: Icons.ExportGifIcon,
  UndoIcon: Icons.UndoIcon,
  RedoIcon: Icons.RedoIcon,
  ClockIcon: Icons.ClockIcon,
  RulerIcon: Icons.RulerIcon,
  GridIcon: Icons.GridIcon,
  OnionSkinIcon: Icons.OnionSkinIcon,
  VelocityHeatmapIcon: Icons.VelocityHeatmapIcon,
  FeedbackIcon: Icons.FeedbackIcon,
  GithubIcon: Icons.GithubIcon,
  PenIcon: Icons.PenIcon,
  ChevronLeftIcon: Icons.ChevronLeftIcon,
  ChevronRightIcon: Icons.ChevronRightIcon,
  SuccessIcon: Icons.SuccessIcon,
  InfoIcon: Icons.InfoIcon,
  WarningIcon: Icons.WarningIcon,
  TriangleWarningIcon: Icons.TriangleWarningIcon,
  ErrorIcon: Icons.ErrorIcon,
  RocketIcon: Icons.RocketIcon,
  LinkIcon: Icons.LinkIcon,
  EyeSlashIcon: Icons.EyeSlashIcon,
  UnlockIcon: Icons.UnlockIcon,
  ArrowCircleIcon: Icons.ArrowCircleIcon,
  PathTabIcon: Icons.PathTabIcon,
  FieldTabIcon: Icons.FieldTabIcon,
  TableTabIcon: Icons.TableTabIcon,
  StatsIcon: Icons.StatsIcon,
  SearchIcon: Icons.SearchIcon,
  ResetIcon: Icons.ResetIcon,
  ChevronUpIcon: Icons.ChevronUpIcon,
  ChevronDownIcon: Icons.ChevronDownIcon,
  LockIcon: Icons.LockIcon,
  SpinnerIcon: Icons.SpinnerIcon,
  SidebarLeftIcon: Icons.SidebarLeftIcon,
  SidebarBottomIcon: Icons.SidebarBottomIcon,
  SidebarHiddenIcon: Icons.SidebarHiddenIcon,
  ChevronRightSolidIcon: Icons.ChevronRightSolidIcon,
  ValidIcon: Icons.ValidIcon,
  ArrowDownIcon: Icons.ArrowDownIcon,
  CloudArrowDownIcon: Icons.CloudArrowDownIcon,
  DocumentPlusIcon: Icons.DocumentPlusIcon,
  FolderPlusIcon: Icons.FolderPlusIcon,
  ArrowDownTrayIcon: Icons.ArrowDownTrayIcon,
  CodeBracketSquareIcon: Icons.CodeBracketSquareIcon,
  ServerStackIcon: Icons.ServerStackIcon,
  MinusIcon: Icons.MinusIcon,
  ResetZoomIcon: Icons.ResetZoomIcon,
  ExitPresentationModeIcon: Icons.ExitPresentationModeIcon,
  ArrowUpIcon: Icons.ArrowUpIcon,
  ClipboardIcon: Icons.ClipboardIcon,
  CheckIcon: Icons.CheckIcon,
  CogIcon: Icons.CogIcon,
  PlusCircleIcon: Icons.PlusCircleIcon,
  MapPinIcon: Icons.MapPinIcon,
  DocumentIcon: Icons.DocumentIcon,
  PhotoIcon: Icons.PhotoIcon,
  SortNameIcon: Icons.SortNameIcon,
  ViewListIcon: Icons.ViewListIcon,
  ViewGridIcon: Icons.ViewGridIcon,
  QuestionMarkIcon: Icons.QuestionMarkIcon,
  EllipsisHorizontalIcon: Icons.EllipsisHorizontalIcon,
  SkipToStartIcon: Icons.SkipToStartIcon,
  SkipToEndIcon: Icons.SkipToEndIcon,
  OnionSkinCurrentPathIcon: Icons.OnionSkinCurrentPathIcon,
  SidebarCollapseIcon: Icons.SidebarCollapseIcon,
  MicrosoftStoreIcon: Icons.MicrosoftStoreIcon,
  RobotPlaceholderIcon: Icons.RobotPlaceholderIcon,
  CriticalIcon: Icons.CriticalIcon,
  DisabledIcon: Icons.DisabledIcon,
  EllipsisVerticalIcon: Icons.EllipsisVerticalIcon,
  KeyboardIcon: Icons.KeyboardIcon,
};
