// Copyright 2026 Matthew Allen. Licensed under the Modified Apache License, Version 2.0.
import * as Icons from "./too-many-animations";
import type { Component } from "svelte";

export type IconName =
  | "account"
  | "account-add"
  | "account-alert"
  | "account-alert-loop"
  | "account-delete"
  | "account-remove"
  | "account-small"
  | "alert"
  | "alert-circle"
  | "alert-circle-loop"
  | "alert-circle-twotone"
  | "alert-circle-twotone-loop"
  | "alert-loop"
  | "alert-square"
  | "alert-square-loop"
  | "alert-square-twotone"
  | "alert-square-twotone-loop"
  | "alert-twotone"
  | "alert-twotone-loop"
  | "align-center"
  | "align-justify"
  | "align-left"
  | "align-right"
  | "arrow-align-bottom"
  | "arrow-align-center"
  | "arrow-align-left"
  | "arrow-align-middle"
  | "arrow-align-right"
  | "arrow-align-top"
  | "arrow-close-down"
  | "arrow-close-left"
  | "arrow-close-right"
  | "arrow-close-up"
  | "arrow-down"
  | "arrow-down-circle"
  | "arrow-down-circle-twotone"
  | "arrow-down-square"
  | "arrow-down-square-twotone"
  | "arrow-left"
  | "arrow-left-circle"
  | "arrow-left-circle-twotone"
  | "arrow-left-square"
  | "arrow-left-square-twotone"
  | "arrow-open-down"
  | "arrow-open-left"
  | "arrow-open-right"
  | "arrow-open-up"
  | "arrow-right"
  | "arrow-right-circle"
  | "arrow-right-circle-twotone"
  | "arrow-right-square"
  | "arrow-right-square-twotone"
  | "arrow-small-down"
  | "arrow-small-left"
  | "arrow-small-right"
  | "arrow-small-up"
  | "arrow-up"
  | "arrow-up-circle"
  | "arrow-up-circle-twotone"
  | "arrow-up-square"
  | "arrow-up-square-twotone"
  | "arrows-diagonal"
  | "arrows-diagonal-rotated"
  | "arrows-horizontal"
  | "arrows-horizontal-alt"
  | "arrows-long-diagonal"
  | "arrows-long-diagonal-rotated"
  | "arrows-vertical"
  | "arrows-vertical-alt"
  | "at"
  | "backup-restore"
  | "beer"
  | "beer-alt"
  | "beer-alt-filled"
  | "beer-alt-filled-loop"
  | "beer-alt-loop"
  | "beer-alt-twotone"
  | "beer-alt-twotone-loop"
  | "beer-filled"
  | "beer-filled-loop"
  | "beer-loop"
  | "beer-twotone"
  | "beer-twotone-loop"
  | "bell"
  | "bell-alert"
  | "bell-alert-filled"
  | "bell-alert-filled-loop"
  | "bell-alert-loop"
  | "bell-alert-twotone"
  | "bell-alert-twotone-loop"
  | "bell-filled"
  | "bell-filled-loop"
  | "bell-loop"
  | "bell-twotone"
  | "bell-twotone-loop"
  | "bluesky"
  | "bluesky-filled"
  | "bluesky-twotone"
  | "brake"
  | "brake-abs"
  | "brake-abs-filled"
  | "brake-abs-twotone"
  | "brake-alert"
  | "brake-alert-filled"
  | "brake-alert-twotone"
  | "brake-filled"
  | "brake-hold"
  | "brake-hold-filled"
  | "brake-hold-twotone"
  | "brake-parking"
  | "brake-parking-filled"
  | "brake-parking-twotone"
  | "brake-twotone"
  | "briefcase"
  | "briefcase-cancel"
  | "briefcase-cancel-filled"
  | "briefcase-cancel-twotone"
  | "briefcase-check"
  | "briefcase-check-filled"
  | "briefcase-check-twotone"
  | "briefcase-filled"
  | "briefcase-minus"
  | "briefcase-minus-filled"
  | "briefcase-minus-twotone"
  | "briefcase-plus"
  | "briefcase-plus-filled"
  | "briefcase-plus-twotone"
  | "briefcase-remove"
  | "briefcase-remove-filled"
  | "briefcase-remove-twotone"
  | "briefcase-twotone"
  | "buy-me-a-coffee"
  | "buy-me-a-coffee-filled"
  | "buy-me-a-coffee-twotone"
  | "cake"
  | "cake-filled"
  | "cake-twotone"
  | "calendar"
  | "calendar-out"
  | "calendar-twotone"
  | "cancel"
  | "cancel-twotone"
  | "car-light"
  | "car-light-alert"
  | "car-light-alert-filled"
  | "car-light-alert-off"
  | "car-light-alert-off-filled"
  | "car-light-alert-off-twotone"
  | "car-light-alert-twotone"
  | "car-light-dimmed"
  | "car-light-dimmed-filled"
  | "car-light-dimmed-off"
  | "car-light-dimmed-off-filled"
  | "car-light-dimmed-off-twotone"
  | "car-light-dimmed-twotone"
  | "car-light-filled"
  | "car-light-off"
  | "car-light-off-filled"
  | "car-light-off-twotone"
  | "car-light-twotone"
  | "cellphone"
  | "cellphone-arrow-down"
  | "cellphone-arrow-down-twotone"
  | "cellphone-arrow-up"
  | "cellphone-arrow-up-twotone"
  | "cellphone-off"
  | "cellphone-off-twotone"
  | "cellphone-screenshot"
  | "cellphone-screenshot-twotone"
  | "cellphone-twotone"
  | "chat"
  | "chat-alert"
  | "chat-alert-filled"
  | "chat-alert-filled-off"
  | "chat-alert-off"
  | "chat-alert-twotone"
  | "chat-alert-twotone-off"
  | "chat-bubble"
  | "chat-bubble-filled"
  | "chat-bubble-filled-off"
  | "chat-bubble-off"
  | "chat-bubble-off-filled"
  | "chat-bubble-off-twotone"
  | "chat-bubble-twotone"
  | "chat-bubble-twotone-off"
  | "chat-filled"
  | "chat-filled-off"
  | "chat-off"
  | "chat-off-filled"
  | "chat-off-twotone"
  | "chat-round"
  | "chat-round-alert"
  | "chat-round-alert-filled"
  | "chat-round-alert-filled-off"
  | "chat-round-alert-off"
  | "chat-round-alert-twotone"
  | "chat-round-alert-twotone-off"
  | "chat-round-dots"
  | "chat-round-dots-filled"
  | "chat-round-dots-filled-off"
  | "chat-round-dots-off"
  | "chat-round-dots-twotone"
  | "chat-round-dots-twotone-off"
  | "chat-round-filled"
  | "chat-round-filled-off"
  | "chat-round-off"
  | "chat-round-off-filled"
  | "chat-round-off-twotone"
  | "chat-round-twotone"
  | "chat-round-twotone-off"
  | "chat-twotone"
  | "chat-twotone-off"
  | "check-all"
  | "check-list-3"
  | "check-list-3-filled"
  | "check-list-3-twotone"
  | "chevron-double-down"
  | "chevron-double-left"
  | "chevron-double-right"
  | "chevron-double-up"
  | "chevron-down"
  | "chevron-down-circle"
  | "chevron-down-circle-twotone"
  | "chevron-down-square"
  | "chevron-down-square-twotone"
  | "chevron-left"
  | "chevron-left-circle"
  | "chevron-left-circle-twotone"
  | "chevron-left-square"
  | "chevron-left-square-twotone"
  | "chevron-right"
  | "chevron-right-circle"
  | "chevron-right-circle-twotone"
  | "chevron-right-square"
  | "chevron-right-square-twotone"
  | "chevron-small-double-down"
  | "chevron-small-double-left"
  | "chevron-small-double-right"
  | "chevron-small-double-up"
  | "chevron-small-down"
  | "chevron-small-left"
  | "chevron-small-right"
  | "chevron-small-triple-down"
  | "chevron-small-triple-left"
  | "chevron-small-triple-right"
  | "chevron-small-triple-up"
  | "chevron-small-up"
  | "chevron-triple-down"
  | "chevron-triple-left"
  | "chevron-triple-right"
  | "chevron-triple-up"
  | "chevron-up"
  | "chevron-up-circle"
  | "chevron-up-circle-twotone"
  | "chevron-up-square"
  | "chevron-up-square-twotone"
  | "circle"
  | "circle-filled"
  | "circle-filled-to-confirm-circle-filled-transition"
  | "circle-to-confirm-circle-transition"
  | "circle-to-confirm-circle-twotone-transition"
  | "circle-twotone"
  | "circle-twotone-to-confirm-circle-transition"
  | "circle-twotone-to-confirm-circle-twotone-transition"
  | "clipboard"
  | "clipboard-arrow"
  | "clipboard-arrow-twotone"
  | "clipboard-check"
  | "clipboard-check-to-clipboard-transition"
  | "clipboard-check-twotone"
  | "clipboard-check-twotone-to-clipboard-twotone-transition"
  | "clipboard-list"
  | "clipboard-list-twotone"
  | "clipboard-minus"
  | "clipboard-minus-twotone"
  | "clipboard-plus"
  | "clipboard-plus-twotone"
  | "clipboard-remove"
  | "clipboard-remove-twotone"
  | "clipboard-to-clipboard-check-transition"
  | "clipboard-twotone"
  | "clipboard-twotone-to-clipboard-check-twotone-transition"
  | "close"
  | "close-circle"
  | "close-circle-filled"
  | "close-circle-twotone"
  | "close-small"
  | "close-square"
  | "close-square-filled"
  | "close-square-twotone"
  | "close-to-menu-alt-transition"
  | "close-to-menu-transition"
  | "cloud"
  | "cloud-alt"
  | "cloud-alt-braces"
  | "cloud-alt-braces-loop"
  | "cloud-alt-download"
  | "cloud-alt-download-filled"
  | "cloud-alt-download-filled-loop"
  | "cloud-alt-download-loop"
  | "cloud-alt-download-twotone"
  | "cloud-alt-download-twotone-loop"
  | "cloud-alt-filled"
  | "cloud-alt-filled-loop"
  | "cloud-alt-loop"
  | "cloud-alt-off"
  | "cloud-alt-off-filled"
  | "cloud-alt-off-filled-loop"
  | "cloud-alt-off-loop"
  | "cloud-alt-off-twotone"
  | "cloud-alt-off-twotone-loop"
  | "cloud-alt-print"
  | "cloud-alt-print-filled"
  | "cloud-alt-print-filled-loop"
  | "cloud-alt-print-loop"
  | "cloud-alt-print-twotone"
  | "cloud-alt-print-twotone-loop"
  | "cloud-alt-tags"
  | "cloud-alt-tags-filled"
  | "cloud-alt-tags-filled-loop"
  | "cloud-alt-tags-loop"
  | "cloud-alt-tags-twotone"
  | "cloud-alt-tags-twotone-loop"
  | "cloud-alt-twotone"
  | "cloud-alt-twotone-loop"
  | "cloud-alt-upload"
  | "cloud-alt-upload-filled"
  | "cloud-alt-upload-filled-loop"
  | "cloud-alt-upload-loop"
  | "cloud-alt-upload-twotone"
  | "cloud-alt-upload-twotone-loop"
  | "cloud-down"
  | "cloud-down-twotone"
  | "cloud-filled"
  | "cloud-off"
  | "cloud-off-filled"
  | "cloud-off-twotone"
  | "cloud-twotone"
  | "cloud-up"
  | "cloud-up-twotone"
  | "coffee"
  | "coffee-arrow"
  | "coffee-arrow-filled"
  | "coffee-arrow-twotone"
  | "coffee-filled"
  | "coffee-filled-loop"
  | "coffee-half-empty-filled-loop"
  | "coffee-half-empty-twotone-loop"
  | "coffee-loop"
  | "coffee-twotone"
  | "coffee-twotone-loop"
  | "cog"
  | "cog-filled"
  | "cog-filled-loop"
  | "cog-loop"
  | "cog-off"
  | "cog-off-filled"
  | "cog-off-filled-loop"
  | "cog-off-loop"
  | "compass"
  | "compass-filled"
  | "compass-filled-loop"
  | "compass-loop"
  | "compass-off"
  | "compass-off-filled"
  | "compass-off-filled-loop"
  | "compass-off-loop"
  | "compass-off-twotone"
  | "compass-off-twotone-loop"
  | "compass-twotone"
  | "compass-twotone-loop"
  | "computer"
  | "computer-filled"
  | "computer-off"
  | "computer-off-filled"
  | "computer-off-twotone"
  | "computer-twotone"
  | "confirm"
  | "confirm-circle"
  | "confirm-circle-filled"
  | "confirm-circle-filled-to-circle-filled-transition"
  | "confirm-circle-to-circle-transition"
  | "confirm-circle-to-circle-twotone-transition"
  | "confirm-circle-twotone"
  | "confirm-circle-twotone-to-circle-transition"
  | "confirm-circle-twotone-to-circle-twotone-transition"
  | "confirm-square"
  | "confirm-square-filled"
  | "confirm-square-filled-to-square-filled-transition"
  | "confirm-square-to-square-transition"
  | "confirm-square-to-square-twotone-transition"
  | "confirm-square-twotone"
  | "confirm-square-twotone-to-square-transition"
  | "confirm-square-twotone-to-square-twotone-transition"
  | "construction"
  | "construction-twotone"
  | "cookie"
  | "cookie-check"
  | "cookie-check-filled"
  | "cookie-check-twotone"
  | "cookie-filled"
  | "cookie-minus"
  | "cookie-minus-filled"
  | "cookie-minus-twotone"
  | "cookie-off"
  | "cookie-off-filled"
  | "cookie-off-twotone"
  | "cookie-plus"
  | "cookie-plus-filled"
  | "cookie-plus-twotone"
  | "cookie-remove"
  | "cookie-remove-filled"
  | "cookie-remove-twotone"
  | "cookie-settings"
  | "cookie-settings-filled"
  | "cookie-settings-twotone"
  | "cookie-twotone"
  | "discord"
  | "discord-twotone"
  | "document"
  | "document-add"
  | "document-add-twotone"
  | "document-code"
  | "document-code-twotone"
  | "document-delete"
  | "document-delete-twotone"
  | "document-list"
  | "document-list-twotone"
  | "document-remove"
  | "document-remove-twotone"
  | "document-report"
  | "document-report-twotone"
  | "document-twotone"
  | "double-arrow-horizontal"
  | "double-arrow-vertical"
  | "download"
  | "download-loop"
  | "download-off"
  | "download-off-loop"
  | "download-off-outline"
  | "download-off-outline-loop"
  | "download-off-twotone"
  | "download-off-twotone-loop"
  | "download-outline"
  | "download-outline-loop"
  | "download-twotone"
  | "download-twotone-loop"
  | "downloading"
  | "downloading-loop"
  | "edit"
  | "edit-filled"
  | "edit-full-filled"
  | "edit-full-twotone"
  | "edit-twotone"
  | "email"
  | "email-alert"
  | "email-alert-filled"
  | "email-alert-twotone"
  | "email-alt-filled"
  | "email-alt-twotone"
  | "email-arrow-down"
  | "email-arrow-down-filled"
  | "email-arrow-down-twotone"
  | "email-arrow-left"
  | "email-arrow-left-filled"
  | "email-arrow-left-twotone"
  | "email-arrow-right"
  | "email-arrow-right-filled"
  | "email-arrow-right-twotone"
  | "email-arrow-up"
  | "email-arrow-up-filled"
  | "email-arrow-up-twotone"
  | "email-check"
  | "email-check-filled"
  | "email-check-twotone"
  | "email-filled"
  | "email-minus"
  | "email-minus-filled"
  | "email-minus-twotone"
  | "email-multiple"
  | "email-multiple-filled"
  | "email-multiple-twotone"
  | "email-opened"
  | "email-opened-alt-filled"
  | "email-opened-alt-twotone"
  | "email-opened-filled"
  | "email-opened-multiple"
  | "email-opened-multiple-filled"
  | "email-opened-multiple-twotone"
  | "email-opened-twotone"
  | "email-plus"
  | "email-plus-filled"
  | "email-plus-twotone"
  | "email-remove"
  | "email-remove-filled"
  | "email-remove-twotone"
  | "email-twotone"
  | "emoji-angry"
  | "emoji-angry-filled"
  | "emoji-angry-twotone"
  | "emoji-cry"
  | "emoji-cry-filled"
  | "emoji-frown"
  | "emoji-frown-filled"
  | "emoji-frown-open"
  | "emoji-frown-open-filled"
  | "emoji-frown-open-twotone"
  | "emoji-frown-twotone"
  | "emoji-grin"
  | "emoji-grin-filled"
  | "emoji-grin-twotone"
  | "emoji-neutral"
  | "emoji-neutral-filled"
  | "emoji-neutral-twotone"
  | "emoji-smile"
  | "emoji-smile-filled"
  | "emoji-smile-twotone"
  | "emoji-smile-wink"
  | "emoji-smile-wink-filled"
  | "emoji-smile-wink-twotone"
  | "engine"
  | "engine-filled"
  | "engine-off"
  | "engine-off-filled"
  | "engine-off-twotone"
  | "engine-twotone"
  | "external-link"
  | "external-link-rounded"
  | "facebook"
  | "file"
  | "file-cancel"
  | "file-cancel-filled"
  | "file-cancel-twotone"
  | "file-document"
  | "file-document-cancel"
  | "file-document-cancel-filled"
  | "file-document-cancel-twotone"
  | "file-document-filled"
  | "file-document-minus"
  | "file-document-minus-filled"
  | "file-document-minus-twotone"
  | "file-document-off"
  | "file-document-off-filled"
  | "file-document-off-twotone"
  | "file-document-plus"
  | "file-document-plus-filled"
  | "file-document-plus-twotone"
  | "file-document-remove"
  | "file-document-remove-filled"
  | "file-document-remove-twotone"
  | "file-document-twotone"
  | "file-download"
  | "file-download-filled"
  | "file-download-twotone"
  | "file-export"
  | "file-export-filled"
  | "file-export-twotone"
  | "file-filled"
  | "file-import"
  | "file-import-filled"
  | "file-import-twotone"
  | "file-minus"
  | "file-minus-filled"
  | "file-minus-twotone"
  | "file-off"
  | "file-off-filled"
  | "file-off-twotone"
  | "file-plus"
  | "file-plus-filled"
  | "file-plus-twotone"
  | "file-remove"
  | "file-remove-filled"
  | "file-remove-twotone"
  | "file-search"
  | "file-search-filled"
  | "file-search-twotone"
  | "file-twotone"
  | "file-upload"
  | "file-upload-filled"
  | "file-upload-twotone"
  | "filter"
  | "filter-alt"
  | "filter-alt-off"
  | "filter-confirm"
  | "filter-confirm-filled"
  | "filter-confirm-twotone"
  | "filter-filled"
  | "filter-minus"
  | "filter-minus-filled"
  | "filter-minus-twotone"
  | "filter-off"
  | "filter-off-filled"
  | "filter-off-twotone"
  | "filter-plus"
  | "filter-plus-filled"
  | "filter-plus-twotone"
  | "filter-remove"
  | "filter-remove-filled"
  | "filter-remove-twotone"
  | "filter-twotone"
  | "folder"
  | "folder-arrow-down"
  | "folder-arrow-down-filled"
  | "folder-arrow-down-twotone"
  | "folder-arrow-left"
  | "folder-arrow-left-filled"
  | "folder-arrow-left-twotone"
  | "folder-arrow-right"
  | "folder-arrow-right-filled"
  | "folder-arrow-right-twotone"
  | "folder-arrow-up"
  | "folder-arrow-up-filled"
  | "folder-arrow-up-twotone"
  | "folder-cancel"
  | "folder-cancel-filled"
  | "folder-cancel-twotone"
  | "folder-check"
  | "folder-check-filled"
  | "folder-check-twotone"
  | "folder-filled"
  | "folder-minus"
  | "folder-minus-filled"
  | "folder-minus-twotone"
  | "folder-multiple"
  | "folder-multiple-filled"
  | "folder-multiple-twotone"
  | "folder-music"
  | "folder-music-filled"
  | "folder-music-twotone"
  | "folder-network"
  | "folder-network-filled"
  | "folder-network-twotone"
  | "folder-off"
  | "folder-off-filled"
  | "folder-off-twotone"
  | "folder-plus"
  | "folder-plus-filled"
  | "folder-plus-twotone"
  | "folder-remove"
  | "folder-remove-filled"
  | "folder-remove-twotone"
  | "folder-settings"
  | "folder-settings-filled"
  | "folder-settings-twotone"
  | "folder-twotone"
  | "folder-zip"
  | "folder-zip-filled"
  | "folder-zip-twotone"
  | "fork-left"
  | "fork-right"
  | "gauge"
  | "gauge-empty"
  | "gauge-empty-twotone"
  | "gauge-full"
  | "gauge-full-twotone"
  | "gauge-loop"
  | "gauge-low"
  | "gauge-low-twotone"
  | "gauge-twotone"
  | "gauge-twotone-loop"
  | "github"
  | "github-loop"
  | "github-twotone"
  | "github-twotone-loop"
  | "grid-3"
  | "grid-3-filled"
  | "grid-3-twotone"
  | "hash"
  | "hash-small"
  | "hazard-lights"
  | "hazard-lights-filled"
  | "hazard-lights-filled-loop"
  | "hazard-lights-loop"
  | "hazard-lights-off"
  | "hazard-lights-off-filled"
  | "hazard-lights-off-filled-loop"
  | "hazard-lights-off-loop"
  | "hazard-lights-off-twotone"
  | "hazard-lights-off-twotone-loop"
  | "hazard-lights-twotone"
  | "hazard-lights-twotone-loop"
  | "heart"
  | "heart-filled"
  | "heart-filled-half"
  | "heart-half"
  | "heart-half-filled"
  | "heart-half-twotone"
  | "heart-twotone"
  | "heart-twotone-half"
  | "heart-twotone-half-filled"
  | "home"
  | "home-alt-twotone"
  | "home-md"
  | "home-md-alt-twotone"
  | "home-md-twotone"
  | "home-simple"
  | "home-simple-filled"
  | "home-simple-twotone"
  | "home-twotone"
  | "iconify1"
  | "iconify2"
  | "iconify2-static"
  | "iconify2-static-twotone"
  | "iconify2-twotone"
  | "image"
  | "image-filled"
  | "image-twotone"
  | "instagram"
  | "laptop"
  | "laptop-filled"
  | "laptop-off"
  | "laptop-off-filled"
  | "laptop-off-twotone"
  | "laptop-twotone"
  | "light-dark"
  | "light-dark-loop"
  | "lightbulb"
  | "lightbulb-filled"
  | "lightbulb-off"
  | "lightbulb-off-filled"
  | "lightbulb-off-filled-loop"
  | "lightbulb-off-loop"
  | "lightbulb-off-twotone"
  | "lightbulb-off-twotone-loop"
  | "lightbulb-twotone"
  | "link"
  | "linkedin"
  | "list"
  | "list-3"
  | "list-3-filled"
  | "list-3-twotone"
  | "list-indented"
  | "list-indented-reversed"
  | "loading-alt-loop"
  | "loading-loop"
  | "loading-twotone-loop"
  | "log-in"
  | "log-out"
  | "login"
  | "logout"
  | "map-marker"
  | "map-marker-alt"
  | "map-marker-alt-filled"
  | "map-marker-alt-filled-loop"
  | "map-marker-alt-loop"
  | "map-marker-alt-off"
  | "map-marker-alt-off-filled"
  | "map-marker-alt-off-filled-loop"
  | "map-marker-alt-off-loop"
  | "map-marker-alt-off-twotone"
  | "map-marker-alt-off-twotone-loop"
  | "map-marker-alt-twotone"
  | "map-marker-alt-twotone-loop"
  | "map-marker-filled"
  | "map-marker-filled-loop"
  | "map-marker-loop"
  | "map-marker-minus"
  | "map-marker-minus-filled"
  | "map-marker-minus-twotone"
  | "map-marker-multiple"
  | "map-marker-multiple-alt"
  | "map-marker-multiple-alt-filled"
  | "map-marker-multiple-alt-filled-loop"
  | "map-marker-multiple-alt-loop"
  | "map-marker-multiple-alt-off"
  | "map-marker-multiple-alt-off-filled"
  | "map-marker-multiple-alt-off-filled-loop"
  | "map-marker-multiple-alt-off-loop"
  | "map-marker-multiple-alt-off-twotone"
  | "map-marker-multiple-alt-off-twotone-loop"
  | "map-marker-multiple-alt-twotone"
  | "map-marker-multiple-alt-twotone-loop"
  | "map-marker-multiple-filled"
  | "map-marker-multiple-filled-loop"
  | "map-marker-multiple-loop"
  | "map-marker-multiple-off"
  | "map-marker-multiple-off-filled"
  | "map-marker-multiple-off-filled-loop"
  | "map-marker-multiple-off-loop"
  | "map-marker-multiple-off-twotone"
  | "map-marker-multiple-off-twotone-loop"
  | "map-marker-multiple-twotone"
  | "map-marker-multiple-twotone-loop"
  | "map-marker-off"
  | "map-marker-off-filled"
  | "map-marker-off-filled-loop"
  | "map-marker-off-loop"
  | "map-marker-off-twotone"
  | "map-marker-off-twotone-loop"
  | "map-marker-plus"
  | "map-marker-plus-filled"
  | "map-marker-plus-twotone"
  | "map-marker-radius"
  | "map-marker-radius-filled"
  | "map-marker-radius-twotone"
  | "map-marker-remove"
  | "map-marker-remove-filled"
  | "map-marker-remove-twotone"
  | "map-marker-twotone"
  | "map-marker-twotone-loop"
  | "marker"
  | "marker-filled"
  | "marker-twotone"
  | "mastodon"
  | "mastodon-filled"
  | "mastodon-twotone"
  | "medical-services"
  | "medical-services-filled"
  | "medical-services-twotone"
  | "menu"
  | "menu-fold-left"
  | "menu-fold-right"
  | "menu-to-close-alt-transition"
  | "menu-to-close-transition"
  | "menu-unfold-left"
  | "menu-unfold-right"
  | "minus"
  | "minus-circle"
  | "minus-circle-filled"
  | "minus-circle-twotone"
  | "minus-square"
  | "minus-square-filled"
  | "minus-square-twotone"
  | "monitor"
  | "monitor-arrow-down"
  | "monitor-arrow-down-filled"
  | "monitor-arrow-down-twotone"
  | "monitor-arrow-up"
  | "monitor-arrow-up-filled"
  | "monitor-arrow-up-twotone"
  | "monitor-filled"
  | "monitor-mutlple"
  | "monitor-mutlple-filled"
  | "monitor-mutlple-twotone"
  | "monitor-off"
  | "monitor-off-filled"
  | "monitor-off-twotone"
  | "monitor-screenshot"
  | "monitor-screenshot-filled"
  | "monitor-screenshot-twotone"
  | "monitor-small"
  | "monitor-small-filled"
  | "monitor-small-off"
  | "monitor-small-off-filled"
  | "monitor-small-off-twotone"
  | "monitor-small-twotone"
  | "monitor-twotone"
  | "moon"
  | "moon-alt"
  | "moon-alt-filled"
  | "moon-alt-filled-loop"
  | "moon-alt-loop"
  | "moon-alt-off"
  | "moon-alt-off-filled"
  | "moon-alt-off-filled-loop"
  | "moon-alt-off-loop"
  | "moon-alt-off-twotone"
  | "moon-alt-off-twotone-loop"
  | "moon-alt-to-sunny-outline-loop-transition"
  | "moon-alt-twotone"
  | "moon-alt-twotone-loop"
  | "moon-filled"
  | "moon-filled-alt-loop"
  | "moon-filled-alt-to-sunny-filled-loop-transition"
  | "moon-filled-loop"
  | "moon-filled-to-sunny-filled-loop-transition"
  | "moon-filled-to-sunny-filled-transition"
  | "moon-loop"
  | "moon-off"
  | "moon-off-filled"
  | "moon-off-filled-loop"
  | "moon-off-loop"
  | "moon-off-twotone"
  | "moon-off-twotone-loop"
  | "moon-rising"
  | "moon-rising-alt"
  | "moon-rising-alt-filled"
  | "moon-rising-alt-filled-loop"
  | "moon-rising-alt-loop"
  | "moon-rising-alt-twotone"
  | "moon-rising-alt-twotone-loop"
  | "moon-rising-filled"
  | "moon-rising-filled-alt-loop"
  | "moon-rising-filled-loop"
  | "moon-rising-loop"
  | "moon-rising-twotone"
  | "moon-rising-twotone-alt-loop"
  | "moon-rising-twotone-loop"
  | "moon-simple"
  | "moon-simple-filled"
  | "moon-simple-off"
  | "moon-simple-off-filled"
  | "moon-simple-off-twotone"
  | "moon-simple-twotone"
  | "moon-to-sunny-outline-loop-transition"
  | "moon-to-sunny-outline-transition"
  | "moon-twotone"
  | "moon-twotone-alt-loop"
  | "moon-twotone-loop"
  | "mushroom"
  | "mushroom-filled"
  | "mushroom-off"
  | "mushroom-off-filled"
  | "mushroom-off-twotone"
  | "mushroom-twotone"
  | "my-location"
  | "my-location-loop"
  | "my-location-off"
  | "my-location-off-loop"
  | "my-location-off-twotone"
  | "my-location-off-twotone-loop"
  | "my-location-twotone"
  | "my-location-twotone-loop"
  | "navigation-left-down"
  | "navigation-left-up"
  | "navigation-right-down"
  | "navigation-right-up"
  | "paint-drop"
  | "paint-drop-filled"
  | "paint-drop-half-filled"
  | "paint-drop-half-filled-twotone"
  | "paint-drop-half-twotone"
  | "paint-drop-twotone"
  | "patreon"
  | "pause"
  | "pause-off"
  | "pause-to-play-filled-transition"
  | "pause-to-play-transition"
  | "peanut"
  | "peanut-filled"
  | "peanut-off"
  | "peanut-off-filled"
  | "peanut-off-twotone"
  | "peanut-twotone"
  | "peertube"
  | "peertube-alt"
  | "pencil"
  | "pencil-alt-twotone"
  | "pencil-twotone"
  | "person"
  | "person-add"
  | "person-add-filled"
  | "person-add-twotone"
  | "person-filled"
  | "person-off"
  | "person-off-filled"
  | "person-off-filled-loop"
  | "person-off-loop"
  | "person-off-twotone"
  | "person-off-twotone-loop"
  | "person-remove"
  | "person-remove-filled"
  | "person-remove-twotone"
  | "person-search"
  | "person-search-filled"
  | "person-search-twotone"
  | "person-twotone"
  | "phone"
  | "phone-add"
  | "phone-add-filled"
  | "phone-add-twotone"
  | "phone-call"
  | "phone-call-filled"
  | "phone-call-filled-loop"
  | "phone-call-loop"
  | "phone-call-twotone"
  | "phone-call-twotone-loop"
  | "phone-filled"
  | "phone-filled-loop"
  | "phone-incoming"
  | "phone-incoming-filled"
  | "phone-incoming-twotone"
  | "phone-loop"
  | "phone-off"
  | "phone-off-filled"
  | "phone-off-filled-loop"
  | "phone-off-loop"
  | "phone-off-twotone"
  | "phone-off-twotone-loop"
  | "phone-outgoing"
  | "phone-outgoing-filled"
  | "phone-outgoing-twotone"
  | "phone-remove"
  | "phone-remove-filled"
  | "phone-remove-twotone"
  | "phone-twotone"
  | "phone-twotone-loop"
  | "pixelfed"
  | "pixelfed-filled"
  | "pixelfed-twotone"
  | "pizza"
  | "pizza-filled"
  | "pizza-off"
  | "pizza-off-filled"
  | "pizza-off-twotone"
  | "pizza-twotone"
  | "play"
  | "play-filled"
  | "play-filled-to-pause-transition"
  | "play-off"
  | "play-off-filled"
  | "play-off-twotone"
  | "play-to-pause-transition"
  | "play-twotone"
  | "pleroma"
  | "plus"
  | "plus-circle"
  | "plus-circle-filled"
  | "plus-circle-twotone"
  | "plus-square"
  | "plus-square-filled"
  | "plus-square-twotone"
  | "question"
  | "question-circle"
  | "question-circle-twotone"
  | "question-square"
  | "question-square-twotone"
  | "reddit"
  | "reddit-circle"
  | "reddit-circle-loop"
  | "reddit-loop"
  | "remove"
  | "rotate-180"
  | "rotate-270"
  | "rotate-90"
  | "round-360"
  | "round-ramp-left"
  | "round-ramp-right"
  | "roundabout-left"
  | "roundabout-right"
  | "rss"
  | "search"
  | "search-filled"
  | "search-twotone"
  | "security"
  | "security-filled"
  | "security-off"
  | "security-off-filled"
  | "security-off-twotone"
  | "security-twotone"
  | "soundcloud"
  | "speed"
  | "speed-loop"
  | "speed-twotone"
  | "speed-twotone-loop"
  | "speedometer"
  | "speedometer-loop"
  | "spotify"
  | "spotify-filled"
  | "spotify-twotone"
  | "square"
  | "square-filled"
  | "square-filled-to-confirm-square-filled-transition"
  | "square-to-confirm-square-transition"
  | "square-to-confirm-square-twotone-transition"
  | "square-twotone"
  | "square-twotone-to-confirm-square-transition"
  | "square-twotone-to-confirm-square-twotone-transition"
  | "star"
  | "star-alt"
  | "star-alt-filled"
  | "star-alt-filled-half"
  | "star-alt-filled-right-half"
  | "star-alt-twotone"
  | "star-alt-twotone-half"
  | "star-alt-twotone-right-half"
  | "star-filled"
  | "star-filled-half"
  | "star-filled-right-half"
  | "star-half"
  | "star-half-alt"
  | "star-half-alt-filled"
  | "star-half-alt-twotone"
  | "star-half-filled"
  | "star-half-twotone"
  | "star-pulsating-filled-loop"
  | "star-pulsating-loop"
  | "star-pulsating-twotone-loop"
  | "star-right-half"
  | "star-right-half-alt"
  | "star-right-half-alt-filled"
  | "star-right-half-alt-twotone"
  | "star-right-half-filled"
  | "star-right-half-twotone"
  | "star-twotone"
  | "star-twotone-half"
  | "star-twotone-right-half"
  | "steering"
  | "steering-off"
  | "sun-rising"
  | "sun-rising-filled"
  | "sun-rising-filled-loop"
  | "sun-rising-loop"
  | "sun-rising-twotone"
  | "sun-rising-twotone-loop"
  | "sunny"
  | "sunny-filled"
  | "sunny-filled-loop"
  | "sunny-filled-loop-to-moon-filled-alt-loop-transition"
  | "sunny-filled-loop-to-moon-filled-loop-transition"
  | "sunny-filled-loop-to-moon-filled-transition"
  | "sunny-loop"
  | "sunny-off"
  | "sunny-off-filled"
  | "sunny-off-filled-loop"
  | "sunny-off-loop"
  | "sunny-off-twotone"
  | "sunny-off-twotone-loop"
  | "sunny-outline-to-moon-alt-loop-transition"
  | "sunny-outline-to-moon-loop-transition"
  | "sunny-outline-to-moon-transition"
  | "sunny-twotone"
  | "sunny-twotone-loop"
  | "switch"
  | "switch-filled"
  | "switch-filled-to-switch-off-filled-transition"
  | "switch-off"
  | "switch-off-filled"
  | "switch-off-filled-to-switch-filled-transition"
  | "switch-off-to-switch-transition"
  | "switch-off-twotone"
  | "switch-off-twotone-to-switch-twotone-transition"
  | "switch-to-switch-off-transition"
  | "switch-twotone"
  | "switch-twotone-to-switch-off-twotone-transition"
  | "tablet"
  | "tablet-arrow-down"
  | "tablet-arrow-down-twotone"
  | "tablet-arrow-up"
  | "tablet-arrow-up-twotone"
  | "tablet-off"
  | "tablet-off-twotone"
  | "tablet-screenshot"
  | "tablet-screenshot-twotone"
  | "tablet-twotone"
  | "taco"
  | "telegram"
  | "text-box"
  | "text-box-multiple"
  | "text-box-multiple-to-text-box-transition"
  | "text-box-multiple-twotone"
  | "text-box-multiple-twotone-to-text-box-twotone-transition"
  | "text-box-to-text-box-multiple-transition"
  | "text-box-twotone"
  | "text-box-twotone-to-text-box-multiple-twotone-transition"
  | "thumbs-down"
  | "thumbs-down-filled"
  | "thumbs-down-twotone"
  | "thumbs-up"
  | "thumbs-up-filled"
  | "thumbs-up-twotone"
  | "tiktok"
  | "trash"
  | "turn-left"
  | "turn-right"
  | "turn-sharp-left"
  | "turn-sharp-right"
  | "turn-slight-left"
  | "turn-slight-right"
  | "twitter"
  | "twitter-filled"
  | "twitter-twotone"
  | "twitter-x"
  | "twitter-x-alt"
  | "u-turn-left"
  | "u-turn-right"
  | "upload"
  | "upload-loop"
  | "upload-off"
  | "upload-off-loop"
  | "upload-off-outline"
  | "upload-off-outline-loop"
  | "upload-off-twotone"
  | "upload-off-twotone-loop"
  | "upload-outline"
  | "upload-outline-loop"
  | "upload-twotone"
  | "upload-twotone-loop"
  | "uploading"
  | "uploading-loop"
  | "valign-baseline"
  | "valign-baseline-twotone"
  | "valign-bottom"
  | "valign-bottom-twotone"
  | "valign-middle"
  | "valign-middle-twotone"
  | "valign-top"
  | "valign-top-twotone"
  | "volume-high"
  | "volume-high-filled"
  | "volume-high-off"
  | "volume-high-off-filled"
  | "volume-high-off-twotone"
  | "volume-high-twotone"
  | "volume-low"
  | "volume-low-filled"
  | "volume-low-off"
  | "volume-low-off-filled"
  | "volume-low-off-twotone"
  | "volume-low-twotone"
  | "volume-medium"
  | "volume-medium-filled"
  | "volume-medium-off"
  | "volume-medium-off-filled"
  | "volume-medium-off-twotone"
  | "volume-medium-twotone"
  | "volume-minus"
  | "volume-minus-filled"
  | "volume-minus-twotone"
  | "volume-plus"
  | "volume-plus-filled"
  | "volume-plus-twotone"
  | "volume-remove"
  | "volume-remove-filled"
  | "volume-remove-twotone"
  | "watch"
  | "watch-loop"
  | "watch-off"
  | "watch-off-loop"
  | "watch-off-twotone"
  | "watch-off-twotone-loop"
  | "watch-twotone"
  | "watch-twotone-loop"
  | "water"
  | "water-filled"
  | "water-off"
  | "water-off-filled"
  | "water-off-twotone"
  | "water-twotone"
  | "weather-cloudy-loop"
  | "youtube"
  | "youtube-filled"
  | "youtube-twotone";

export const iconMap: Record<string, Component<any>> = {
  account: Icons.AccountIcon,
  "account-add": Icons.AccountAddIcon,
  "account-alert": Icons.AccountAlertIcon,
  "account-alert-loop": Icons.AccountAlertLoopIcon,
  "account-delete": Icons.AccountDeleteIcon,
  "account-remove": Icons.AccountRemoveIcon,
  "account-small": Icons.AccountSmallIcon,
  alert: Icons.AlertIcon,
  "alert-circle": Icons.AlertCircleIcon,
  "alert-circle-loop": Icons.AlertCircleLoopIcon,
  "alert-circle-twotone": Icons.AlertCircleTwotoneIcon,
  "alert-circle-twotone-loop": Icons.AlertCircleTwotoneLoopIcon,
  "alert-loop": Icons.AlertLoopIcon,
  "alert-square": Icons.AlertSquareIcon,
  "alert-square-loop": Icons.AlertSquareLoopIcon,
  "alert-square-twotone": Icons.AlertSquareTwotoneIcon,
  "alert-square-twotone-loop": Icons.AlertSquareTwotoneLoopIcon,
  "alert-twotone": Icons.AlertTwotoneIcon,
  "alert-twotone-loop": Icons.AlertTwotoneLoopIcon,
  "align-center": Icons.AlignCenterIcon,
  "align-justify": Icons.AlignJustifyIcon,
  "align-left": Icons.AlignLeftIcon,
  "align-right": Icons.AlignRightIcon,
  "arrow-align-bottom": Icons.ArrowAlignBottomIcon,
  "arrow-align-center": Icons.ArrowAlignCenterIcon,
  "arrow-align-left": Icons.ArrowAlignLeftIcon,
  "arrow-align-middle": Icons.ArrowAlignMiddleIcon,
  "arrow-align-right": Icons.ArrowAlignRightIcon,
  "arrow-align-top": Icons.ArrowAlignTopIcon,
  "arrow-close-down": Icons.ArrowCloseDownIcon,
  "arrow-close-left": Icons.ArrowCloseLeftIcon,
  "arrow-close-right": Icons.ArrowCloseRightIcon,
  "arrow-close-up": Icons.ArrowCloseUpIcon,
  "arrow-down": Icons.ArrowDownIcon,
  "arrow-down-circle": Icons.ArrowDownCircleIcon,
  "arrow-down-circle-twotone": Icons.ArrowDownCircleTwotoneIcon,
  "arrow-down-square": Icons.ArrowDownSquareIcon,
  "arrow-down-square-twotone": Icons.ArrowDownSquareTwotoneIcon,
  "arrow-left": Icons.ArrowLeftIcon,
  "arrow-left-circle": Icons.ArrowLeftCircleIcon,
  "arrow-left-circle-twotone": Icons.ArrowLeftCircleTwotoneIcon,
  "arrow-left-square": Icons.ArrowLeftSquareIcon,
  "arrow-left-square-twotone": Icons.ArrowLeftSquareTwotoneIcon,
  "arrow-open-down": Icons.ArrowOpenDownIcon,
  "arrow-open-left": Icons.ArrowOpenLeftIcon,
  "arrow-open-right": Icons.ArrowOpenRightIcon,
  "arrow-open-up": Icons.ArrowOpenUpIcon,
  "arrow-right": Icons.ArrowRightIcon,
  "arrow-right-circle": Icons.ArrowRightCircleIcon,
  "arrow-right-circle-twotone": Icons.ArrowRightCircleTwotoneIcon,
  "arrow-right-square": Icons.ArrowRightSquareIcon,
  "arrow-right-square-twotone": Icons.ArrowRightSquareTwotoneIcon,
  "arrow-small-down": Icons.ArrowSmallDownIcon,
  "arrow-small-left": Icons.ArrowSmallLeftIcon,
  "arrow-small-right": Icons.ArrowSmallRightIcon,
  "arrow-small-up": Icons.ArrowSmallUpIcon,
  "arrow-up": Icons.ArrowUpIcon,
  "arrow-up-circle": Icons.ArrowUpCircleIcon,
  "arrow-up-circle-twotone": Icons.ArrowUpCircleTwotoneIcon,
  "arrow-up-square": Icons.ArrowUpSquareIcon,
  "arrow-up-square-twotone": Icons.ArrowUpSquareTwotoneIcon,
  "arrows-diagonal": Icons.ArrowsDiagonalIcon,
  "arrows-diagonal-rotated": Icons.ArrowsDiagonalRotatedIcon,
  "arrows-horizontal": Icons.ArrowsHorizontalIcon,
  "arrows-horizontal-alt": Icons.ArrowsHorizontalAltIcon,
  "arrows-long-diagonal": Icons.ArrowsLongDiagonalIcon,
  "arrows-long-diagonal-rotated": Icons.ArrowsLongDiagonalRotatedIcon,
  "arrows-vertical": Icons.ArrowsVerticalIcon,
  "arrows-vertical-alt": Icons.ArrowsVerticalAltIcon,
  at: Icons.AtIcon,
  "backup-restore": Icons.BackupRestoreIcon,
  beer: Icons.BeerIcon,
  "beer-alt": Icons.BeerAltIcon,
  "beer-alt-filled": Icons.BeerAltFilledIcon,
  "beer-alt-filled-loop": Icons.BeerAltFilledLoopIcon,
  "beer-alt-loop": Icons.BeerAltLoopIcon,
  "beer-alt-twotone": Icons.BeerAltTwotoneIcon,
  "beer-alt-twotone-loop": Icons.BeerAltTwotoneLoopIcon,
  "beer-filled": Icons.BeerFilledIcon,
  "beer-filled-loop": Icons.BeerFilledLoopIcon,
  "beer-loop": Icons.BeerLoopIcon,
  "beer-twotone": Icons.BeerTwotoneIcon,
  "beer-twotone-loop": Icons.BeerTwotoneLoopIcon,
  bell: Icons.BellIcon,
  "bell-alert": Icons.BellAlertIcon,
  "bell-alert-filled": Icons.BellAlertFilledIcon,
  "bell-alert-filled-loop": Icons.BellAlertFilledLoopIcon,
  "bell-alert-loop": Icons.BellAlertLoopIcon,
  "bell-alert-twotone": Icons.BellAlertTwotoneIcon,
  "bell-alert-twotone-loop": Icons.BellAlertTwotoneLoopIcon,
  "bell-filled": Icons.BellFilledIcon,
  "bell-filled-loop": Icons.BellFilledLoopIcon,
  "bell-loop": Icons.BellLoopIcon,
  "bell-twotone": Icons.BellTwotoneIcon,
  "bell-twotone-loop": Icons.BellTwotoneLoopIcon,
  bluesky: Icons.BlueskyIcon,
  "bluesky-filled": Icons.BlueskyFilledIcon,
  "bluesky-twotone": Icons.BlueskyTwotoneIcon,
  brake: Icons.BrakeIcon,
  "brake-abs": Icons.BrakeAbsIcon,
  "brake-abs-filled": Icons.BrakeAbsFilledIcon,
  "brake-abs-twotone": Icons.BrakeAbsTwotoneIcon,
  "brake-alert": Icons.BrakeAlertIcon,
  "brake-alert-filled": Icons.BrakeAlertFilledIcon,
  "brake-alert-twotone": Icons.BrakeAlertTwotoneIcon,
  "brake-filled": Icons.BrakeFilledIcon,
  "brake-hold": Icons.BrakeHoldIcon,
  "brake-hold-filled": Icons.BrakeHoldFilledIcon,
  "brake-hold-twotone": Icons.BrakeHoldTwotoneIcon,
  "brake-parking": Icons.BrakeParkingIcon,
  "brake-parking-filled": Icons.BrakeParkingFilledIcon,
  "brake-parking-twotone": Icons.BrakeParkingTwotoneIcon,
  "brake-twotone": Icons.BrakeTwotoneIcon,
  briefcase: Icons.BriefcaseIcon,
  "briefcase-cancel": Icons.BriefcaseCancelIcon,
  "briefcase-cancel-filled": Icons.BriefcaseCancelFilledIcon,
  "briefcase-cancel-twotone": Icons.BriefcaseCancelTwotoneIcon,
  "briefcase-check": Icons.BriefcaseCheckIcon,
  "briefcase-check-filled": Icons.BriefcaseCheckFilledIcon,
  "briefcase-check-twotone": Icons.BriefcaseCheckTwotoneIcon,
  "briefcase-filled": Icons.BriefcaseFilledIcon,
  "briefcase-minus": Icons.BriefcaseMinusIcon,
  "briefcase-minus-filled": Icons.BriefcaseMinusFilledIcon,
  "briefcase-minus-twotone": Icons.BriefcaseMinusTwotoneIcon,
  "briefcase-plus": Icons.BriefcasePlusIcon,
  "briefcase-plus-filled": Icons.BriefcasePlusFilledIcon,
  "briefcase-plus-twotone": Icons.BriefcasePlusTwotoneIcon,
  "briefcase-remove": Icons.BriefcaseRemoveIcon,
  "briefcase-remove-filled": Icons.BriefcaseRemoveFilledIcon,
  "briefcase-remove-twotone": Icons.BriefcaseRemoveTwotoneIcon,
  "briefcase-twotone": Icons.BriefcaseTwotoneIcon,
  "buy-me-a-coffee": Icons.BuyMeACoffeeIcon,
  "buy-me-a-coffee-filled": Icons.BuyMeACoffeeFilledIcon,
  "buy-me-a-coffee-twotone": Icons.BuyMeACoffeeTwotoneIcon,
  cake: Icons.CakeIcon,
  "cake-filled": Icons.CakeFilledIcon,
  "cake-twotone": Icons.CakeTwotoneIcon,
  calendar: Icons.CalendarIcon,
  "calendar-out": Icons.CalendarOutIcon,
  "calendar-twotone": Icons.CalendarTwotoneIcon,
  cancel: Icons.CancelIcon,
  "cancel-twotone": Icons.CancelTwotoneIcon,
  "car-light": Icons.CarLightIcon,
  "car-light-alert": Icons.CarLightAlertIcon,
  "car-light-alert-filled": Icons.CarLightAlertFilledIcon,
  "car-light-alert-off": Icons.CarLightAlertOffIcon,
  "car-light-alert-off-filled": Icons.CarLightAlertOffFilledIcon,
  "car-light-alert-off-twotone": Icons.CarLightAlertOffTwotoneIcon,
  "car-light-alert-twotone": Icons.CarLightAlertTwotoneIcon,
  "car-light-dimmed": Icons.CarLightDimmedIcon,
  "car-light-dimmed-filled": Icons.CarLightDimmedFilledIcon,
  "car-light-dimmed-off": Icons.CarLightDimmedOffIcon,
  "car-light-dimmed-off-filled": Icons.CarLightDimmedOffFilledIcon,
  "car-light-dimmed-off-twotone": Icons.CarLightDimmedOffTwotoneIcon,
  "car-light-dimmed-twotone": Icons.CarLightDimmedTwotoneIcon,
  "car-light-filled": Icons.CarLightFilledIcon,
  "car-light-off": Icons.CarLightOffIcon,
  "car-light-off-filled": Icons.CarLightOffFilledIcon,
  "car-light-off-twotone": Icons.CarLightOffTwotoneIcon,
  "car-light-twotone": Icons.CarLightTwotoneIcon,
  cellphone: Icons.CellphoneIcon,
  "cellphone-arrow-down": Icons.CellphoneArrowDownIcon,
  "cellphone-arrow-down-twotone": Icons.CellphoneArrowDownTwotoneIcon,
  "cellphone-arrow-up": Icons.CellphoneArrowUpIcon,
  "cellphone-arrow-up-twotone": Icons.CellphoneArrowUpTwotoneIcon,
  "cellphone-off": Icons.CellphoneOffIcon,
  "cellphone-off-twotone": Icons.CellphoneOffTwotoneIcon,
  "cellphone-screenshot": Icons.CellphoneScreenshotIcon,
  "cellphone-screenshot-twotone": Icons.CellphoneScreenshotTwotoneIcon,
  "cellphone-twotone": Icons.CellphoneTwotoneIcon,
  chat: Icons.ChatIcon,
  "chat-alert": Icons.ChatAlertIcon,
  "chat-alert-filled": Icons.ChatAlertFilledIcon,
  "chat-alert-filled-off": Icons.ChatAlertFilledOffIcon,
  "chat-alert-off": Icons.ChatAlertOffIcon,
  "chat-alert-twotone": Icons.ChatAlertTwotoneIcon,
  "chat-alert-twotone-off": Icons.ChatAlertTwotoneOffIcon,
  "chat-bubble": Icons.ChatBubbleIcon,
  "chat-bubble-filled": Icons.ChatBubbleFilledIcon,
  "chat-bubble-filled-off": Icons.ChatBubbleFilledOffIcon,
  "chat-bubble-off": Icons.ChatBubbleOffIcon,
  "chat-bubble-off-filled": Icons.ChatBubbleOffFilledIcon,
  "chat-bubble-off-twotone": Icons.ChatBubbleOffTwotoneIcon,
  "chat-bubble-twotone": Icons.ChatBubbleTwotoneIcon,
  "chat-bubble-twotone-off": Icons.ChatBubbleTwotoneOffIcon,
  "chat-filled": Icons.ChatFilledIcon,
  "chat-filled-off": Icons.ChatFilledOffIcon,
  "chat-off": Icons.ChatOffIcon,
  "chat-off-filled": Icons.ChatOffFilledIcon,
  "chat-off-twotone": Icons.ChatOffTwotoneIcon,
  "chat-round": Icons.ChatRoundIcon,
  "chat-round-alert": Icons.ChatRoundAlertIcon,
  "chat-round-alert-filled": Icons.ChatRoundAlertFilledIcon,
  "chat-round-alert-filled-off": Icons.ChatRoundAlertFilledOffIcon,
  "chat-round-alert-off": Icons.ChatRoundAlertOffIcon,
  "chat-round-alert-twotone": Icons.ChatRoundAlertTwotoneIcon,
  "chat-round-alert-twotone-off": Icons.ChatRoundAlertTwotoneOffIcon,
  "chat-round-dots": Icons.ChatRoundDotsIcon,
  "chat-round-dots-filled": Icons.ChatRoundDotsFilledIcon,
  "chat-round-dots-filled-off": Icons.ChatRoundDotsFilledOffIcon,
  "chat-round-dots-off": Icons.ChatRoundDotsOffIcon,
  "chat-round-dots-twotone": Icons.ChatRoundDotsTwotoneIcon,
  "chat-round-dots-twotone-off": Icons.ChatRoundDotsTwotoneOffIcon,
  "chat-round-filled": Icons.ChatRoundFilledIcon,
  "chat-round-filled-off": Icons.ChatRoundFilledOffIcon,
  "chat-round-off": Icons.ChatRoundOffIcon,
  "chat-round-off-filled": Icons.ChatRoundOffFilledIcon,
  "chat-round-off-twotone": Icons.ChatRoundOffTwotoneIcon,
  "chat-round-twotone": Icons.ChatRoundTwotoneIcon,
  "chat-round-twotone-off": Icons.ChatRoundTwotoneOffIcon,
  "chat-twotone": Icons.ChatTwotoneIcon,
  "chat-twotone-off": Icons.ChatTwotoneOffIcon,
  "check-all": Icons.CheckAllIcon,
  "check-list-3": Icons.CheckList3Icon,
  "check-list-3-filled": Icons.CheckList3FilledIcon,
  "check-list-3-twotone": Icons.CheckList3TwotoneIcon,
  "chevron-double-down": Icons.ChevronDoubleDownIcon,
  "chevron-double-left": Icons.ChevronDoubleLeftIcon,
  "chevron-double-right": Icons.ChevronDoubleRightIcon,
  "chevron-double-up": Icons.ChevronDoubleUpIcon,
  "chevron-down": Icons.ChevronDownIcon,
  "chevron-down-circle": Icons.ChevronDownCircleIcon,
  "chevron-down-circle-twotone": Icons.ChevronDownCircleTwotoneIcon,
  "chevron-down-square": Icons.ChevronDownSquareIcon,
  "chevron-down-square-twotone": Icons.ChevronDownSquareTwotoneIcon,
  "chevron-left": Icons.ChevronLeftIcon,
  "chevron-left-circle": Icons.ChevronLeftCircleIcon,
  "chevron-left-circle-twotone": Icons.ChevronLeftCircleTwotoneIcon,
  "chevron-left-square": Icons.ChevronLeftSquareIcon,
  "chevron-left-square-twotone": Icons.ChevronLeftSquareTwotoneIcon,
  "chevron-right": Icons.ChevronRightIcon,
  "chevron-right-circle": Icons.ChevronRightCircleIcon,
  "chevron-right-circle-twotone": Icons.ChevronRightCircleTwotoneIcon,
  "chevron-right-square": Icons.ChevronRightSquareIcon,
  "chevron-right-square-twotone": Icons.ChevronRightSquareTwotoneIcon,
  "chevron-small-double-down": Icons.ChevronSmallDoubleDownIcon,
  "chevron-small-double-left": Icons.ChevronSmallDoubleLeftIcon,
  "chevron-small-double-right": Icons.ChevronSmallDoubleRightIcon,
  "chevron-small-double-up": Icons.ChevronSmallDoubleUpIcon,
  "chevron-small-down": Icons.ChevronSmallDownIcon,
  "chevron-small-left": Icons.ChevronSmallLeftIcon,
  "chevron-small-right": Icons.ChevronSmallRightIcon,
  "chevron-small-triple-down": Icons.ChevronSmallTripleDownIcon,
  "chevron-small-triple-left": Icons.ChevronSmallTripleLeftIcon,
  "chevron-small-triple-right": Icons.ChevronSmallTripleRightIcon,
  "chevron-small-triple-up": Icons.ChevronSmallTripleUpIcon,
  "chevron-small-up": Icons.ChevronSmallUpIcon,
  "chevron-triple-down": Icons.ChevronTripleDownIcon,
  "chevron-triple-left": Icons.ChevronTripleLeftIcon,
  "chevron-triple-right": Icons.ChevronTripleRightIcon,
  "chevron-triple-up": Icons.ChevronTripleUpIcon,
  "chevron-up": Icons.ChevronUpIcon,
  "chevron-up-circle": Icons.ChevronUpCircleIcon,
  "chevron-up-circle-twotone": Icons.ChevronUpCircleTwotoneIcon,
  "chevron-up-square": Icons.ChevronUpSquareIcon,
  "chevron-up-square-twotone": Icons.ChevronUpSquareTwotoneIcon,
  circle: Icons.CircleIcon,
  "circle-filled": Icons.CircleFilledIcon,
  "circle-filled-to-confirm-circle-filled-transition":
    Icons.CircleFilledToConfirmCircleFilledTransitionIcon,
  "circle-to-confirm-circle-transition":
    Icons.CircleToConfirmCircleTransitionIcon,
  "circle-to-confirm-circle-twotone-transition":
    Icons.CircleToConfirmCircleTwotoneTransitionIcon,
  "circle-twotone": Icons.CircleTwotoneIcon,
  "circle-twotone-to-confirm-circle-transition":
    Icons.CircleTwotoneToConfirmCircleTransitionIcon,
  "circle-twotone-to-confirm-circle-twotone-transition":
    Icons.CircleTwotoneToConfirmCircleTwotoneTransitionIcon,
  clipboard: Icons.ClipboardIcon,
  "clipboard-arrow": Icons.ClipboardArrowIcon,
  "clipboard-arrow-twotone": Icons.ClipboardArrowTwotoneIcon,
  "clipboard-check": Icons.ClipboardCheckIcon,
  "clipboard-check-to-clipboard-transition":
    Icons.ClipboardCheckToClipboardTransitionIcon,
  "clipboard-check-twotone": Icons.ClipboardCheckTwotoneIcon,
  "clipboard-check-twotone-to-clipboard-twotone-transition":
    Icons.ClipboardCheckTwotoneToClipboardTwotoneTransitionIcon,
  "clipboard-list": Icons.ClipboardListIcon,
  "clipboard-list-twotone": Icons.ClipboardListTwotoneIcon,
  "clipboard-minus": Icons.ClipboardMinusIcon,
  "clipboard-minus-twotone": Icons.ClipboardMinusTwotoneIcon,
  "clipboard-plus": Icons.ClipboardPlusIcon,
  "clipboard-plus-twotone": Icons.ClipboardPlusTwotoneIcon,
  "clipboard-remove": Icons.ClipboardRemoveIcon,
  "clipboard-remove-twotone": Icons.ClipboardRemoveTwotoneIcon,
  "clipboard-to-clipboard-check-transition":
    Icons.ClipboardToClipboardCheckTransitionIcon,
  "clipboard-twotone": Icons.ClipboardTwotoneIcon,
  "clipboard-twotone-to-clipboard-check-twotone-transition":
    Icons.ClipboardTwotoneToClipboardCheckTwotoneTransitionIcon,
  close: Icons.CloseIcon,
  "close-circle": Icons.CloseCircleIcon,
  "close-circle-filled": Icons.CloseCircleFilledIcon,
  "close-circle-twotone": Icons.CloseCircleTwotoneIcon,
  "close-small": Icons.CloseSmallIcon,
  "close-square": Icons.CloseSquareIcon,
  "close-square-filled": Icons.CloseSquareFilledIcon,
  "close-square-twotone": Icons.CloseSquareTwotoneIcon,
  "close-to-menu-alt-transition": Icons.CloseToMenuAltTransitionIcon,
  "close-to-menu-transition": Icons.CloseToMenuTransitionIcon,
  cloud: Icons.CloudIcon,
  "cloud-alt": Icons.CloudAltIcon,
  "cloud-alt-braces": Icons.CloudAltBracesIcon,
  "cloud-alt-braces-loop": Icons.CloudAltBracesLoopIcon,
  "cloud-alt-download": Icons.CloudAltDownloadIcon,
  "cloud-alt-download-filled": Icons.CloudAltDownloadFilledIcon,
  "cloud-alt-download-filled-loop": Icons.CloudAltDownloadFilledLoopIcon,
  "cloud-alt-download-loop": Icons.CloudAltDownloadLoopIcon,
  "cloud-alt-download-twotone": Icons.CloudAltDownloadTwotoneIcon,
  "cloud-alt-download-twotone-loop": Icons.CloudAltDownloadTwotoneLoopIcon,
  "cloud-alt-filled": Icons.CloudAltFilledIcon,
  "cloud-alt-filled-loop": Icons.CloudAltFilledLoopIcon,
  "cloud-alt-loop": Icons.CloudAltLoopIcon,
  "cloud-alt-off": Icons.CloudAltOffIcon,
  "cloud-alt-off-filled": Icons.CloudAltOffFilledIcon,
  "cloud-alt-off-filled-loop": Icons.CloudAltOffFilledLoopIcon,
  "cloud-alt-off-loop": Icons.CloudAltOffLoopIcon,
  "cloud-alt-off-twotone": Icons.CloudAltOffTwotoneIcon,
  "cloud-alt-off-twotone-loop": Icons.CloudAltOffTwotoneLoopIcon,
  "cloud-alt-print": Icons.CloudAltPrintIcon,
  "cloud-alt-print-filled": Icons.CloudAltPrintFilledIcon,
  "cloud-alt-print-filled-loop": Icons.CloudAltPrintFilledLoopIcon,
  "cloud-alt-print-loop": Icons.CloudAltPrintLoopIcon,
  "cloud-alt-print-twotone": Icons.CloudAltPrintTwotoneIcon,
  "cloud-alt-print-twotone-loop": Icons.CloudAltPrintTwotoneLoopIcon,
  "cloud-alt-tags": Icons.CloudAltTagsIcon,
  "cloud-alt-tags-filled": Icons.CloudAltTagsFilledIcon,
  "cloud-alt-tags-filled-loop": Icons.CloudAltTagsFilledLoopIcon,
  "cloud-alt-tags-loop": Icons.CloudAltTagsLoopIcon,
  "cloud-alt-tags-twotone": Icons.CloudAltTagsTwotoneIcon,
  "cloud-alt-tags-twotone-loop": Icons.CloudAltTagsTwotoneLoopIcon,
  "cloud-alt-twotone": Icons.CloudAltTwotoneIcon,
  "cloud-alt-twotone-loop": Icons.CloudAltTwotoneLoopIcon,
  "cloud-alt-upload": Icons.CloudAltUploadIcon,
  "cloud-alt-upload-filled": Icons.CloudAltUploadFilledIcon,
  "cloud-alt-upload-filled-loop": Icons.CloudAltUploadFilledLoopIcon,
  "cloud-alt-upload-loop": Icons.CloudAltUploadLoopIcon,
  "cloud-alt-upload-twotone": Icons.CloudAltUploadTwotoneIcon,
  "cloud-alt-upload-twotone-loop": Icons.CloudAltUploadTwotoneLoopIcon,
  "cloud-down": Icons.CloudDownIcon,
  "cloud-down-twotone": Icons.CloudDownTwotoneIcon,
  "cloud-filled": Icons.CloudFilledIcon,
  "cloud-off": Icons.CloudOffIcon,
  "cloud-off-filled": Icons.CloudOffFilledIcon,
  "cloud-off-twotone": Icons.CloudOffTwotoneIcon,
  "cloud-twotone": Icons.CloudTwotoneIcon,
  "cloud-up": Icons.CloudUpIcon,
  "cloud-up-twotone": Icons.CloudUpTwotoneIcon,
  coffee: Icons.CoffeeIcon,
  "coffee-arrow": Icons.CoffeeArrowIcon,
  "coffee-arrow-filled": Icons.CoffeeArrowFilledIcon,
  "coffee-arrow-twotone": Icons.CoffeeArrowTwotoneIcon,
  "coffee-filled": Icons.CoffeeFilledIcon,
  "coffee-filled-loop": Icons.CoffeeFilledLoopIcon,
  "coffee-half-empty-filled-loop": Icons.CoffeeHalfEmptyFilledLoopIcon,
  "coffee-half-empty-twotone-loop": Icons.CoffeeHalfEmptyTwotoneLoopIcon,
  "coffee-loop": Icons.CoffeeLoopIcon,
  "coffee-twotone": Icons.CoffeeTwotoneIcon,
  "coffee-twotone-loop": Icons.CoffeeTwotoneLoopIcon,
  cog: Icons.CogIcon,
  "cog-filled": Icons.CogFilledIcon,
  "cog-filled-loop": Icons.CogFilledLoopIcon,
  "cog-loop": Icons.CogLoopIcon,
  "cog-off": Icons.CogOffIcon,
  "cog-off-filled": Icons.CogOffFilledIcon,
  "cog-off-filled-loop": Icons.CogOffFilledLoopIcon,
  "cog-off-loop": Icons.CogOffLoopIcon,
  compass: Icons.CompassIcon,
  "compass-filled": Icons.CompassFilledIcon,
  "compass-filled-loop": Icons.CompassFilledLoopIcon,
  "compass-loop": Icons.CompassLoopIcon,
  "compass-off": Icons.CompassOffIcon,
  "compass-off-filled": Icons.CompassOffFilledIcon,
  "compass-off-filled-loop": Icons.CompassOffFilledLoopIcon,
  "compass-off-loop": Icons.CompassOffLoopIcon,
  "compass-off-twotone": Icons.CompassOffTwotoneIcon,
  "compass-off-twotone-loop": Icons.CompassOffTwotoneLoopIcon,
  "compass-twotone": Icons.CompassTwotoneIcon,
  "compass-twotone-loop": Icons.CompassTwotoneLoopIcon,
  computer: Icons.ComputerIcon,
  "computer-filled": Icons.ComputerFilledIcon,
  "computer-off": Icons.ComputerOffIcon,
  "computer-off-filled": Icons.ComputerOffFilledIcon,
  "computer-off-twotone": Icons.ComputerOffTwotoneIcon,
  "computer-twotone": Icons.ComputerTwotoneIcon,
  confirm: Icons.ConfirmIcon,
  "confirm-circle": Icons.ConfirmCircleIcon,
  "confirm-circle-filled": Icons.ConfirmCircleFilledIcon,
  "confirm-circle-filled-to-circle-filled-transition":
    Icons.ConfirmCircleFilledToCircleFilledTransitionIcon,
  "confirm-circle-to-circle-transition":
    Icons.ConfirmCircleToCircleTransitionIcon,
  "confirm-circle-to-circle-twotone-transition":
    Icons.ConfirmCircleToCircleTwotoneTransitionIcon,
  "confirm-circle-twotone": Icons.ConfirmCircleTwotoneIcon,
  "confirm-circle-twotone-to-circle-transition":
    Icons.ConfirmCircleTwotoneToCircleTransitionIcon,
  "confirm-circle-twotone-to-circle-twotone-transition":
    Icons.ConfirmCircleTwotoneToCircleTwotoneTransitionIcon,
  "confirm-square": Icons.ConfirmSquareIcon,
  "confirm-square-filled": Icons.ConfirmSquareFilledIcon,
  "confirm-square-filled-to-square-filled-transition":
    Icons.ConfirmSquareFilledToSquareFilledTransitionIcon,
  "confirm-square-to-square-transition":
    Icons.ConfirmSquareToSquareTransitionIcon,
  "confirm-square-to-square-twotone-transition":
    Icons.ConfirmSquareToSquareTwotoneTransitionIcon,
  "confirm-square-twotone": Icons.ConfirmSquareTwotoneIcon,
  "confirm-square-twotone-to-square-transition":
    Icons.ConfirmSquareTwotoneToSquareTransitionIcon,
  "confirm-square-twotone-to-square-twotone-transition":
    Icons.ConfirmSquareTwotoneToSquareTwotoneTransitionIcon,
  construction: Icons.ConstructionIcon,
  "construction-twotone": Icons.ConstructionTwotoneIcon,
  cookie: Icons.CookieIcon,
  "cookie-check": Icons.CookieCheckIcon,
  "cookie-check-filled": Icons.CookieCheckFilledIcon,
  "cookie-check-twotone": Icons.CookieCheckTwotoneIcon,
  "cookie-filled": Icons.CookieFilledIcon,
  "cookie-minus": Icons.CookieMinusIcon,
  "cookie-minus-filled": Icons.CookieMinusFilledIcon,
  "cookie-minus-twotone": Icons.CookieMinusTwotoneIcon,
  "cookie-off": Icons.CookieOffIcon,
  "cookie-off-filled": Icons.CookieOffFilledIcon,
  "cookie-off-twotone": Icons.CookieOffTwotoneIcon,
  "cookie-plus": Icons.CookiePlusIcon,
  "cookie-plus-filled": Icons.CookiePlusFilledIcon,
  "cookie-plus-twotone": Icons.CookiePlusTwotoneIcon,
  "cookie-remove": Icons.CookieRemoveIcon,
  "cookie-remove-filled": Icons.CookieRemoveFilledIcon,
  "cookie-remove-twotone": Icons.CookieRemoveTwotoneIcon,
  "cookie-settings": Icons.CookieSettingsIcon,
  "cookie-settings-filled": Icons.CookieSettingsFilledIcon,
  "cookie-settings-twotone": Icons.CookieSettingsTwotoneIcon,
  "cookie-twotone": Icons.CookieTwotoneIcon,
  discord: Icons.DiscordIcon,
  "discord-twotone": Icons.DiscordTwotoneIcon,
  document: Icons.DocumentIcon,
  "document-add": Icons.DocumentAddIcon,
  "document-add-twotone": Icons.DocumentAddTwotoneIcon,
  "document-code": Icons.DocumentCodeIcon,
  "document-code-twotone": Icons.DocumentCodeTwotoneIcon,
  "document-delete": Icons.DocumentDeleteIcon,
  "document-delete-twotone": Icons.DocumentDeleteTwotoneIcon,
  "document-list": Icons.DocumentListIcon,
  "document-list-twotone": Icons.DocumentListTwotoneIcon,
  "document-remove": Icons.DocumentRemoveIcon,
  "document-remove-twotone": Icons.DocumentRemoveTwotoneIcon,
  "document-report": Icons.DocumentReportIcon,
  "document-report-twotone": Icons.DocumentReportTwotoneIcon,
  "document-twotone": Icons.DocumentTwotoneIcon,
  "double-arrow-horizontal": Icons.DoubleArrowHorizontalIcon,
  "double-arrow-vertical": Icons.DoubleArrowVerticalIcon,
  download: Icons.DownloadIcon,
  "download-loop": Icons.DownloadLoopIcon,
  "download-off": Icons.DownloadOffIcon,
  "download-off-loop": Icons.DownloadOffLoopIcon,
  "download-off-outline": Icons.DownloadOffOutlineIcon,
  "download-off-outline-loop": Icons.DownloadOffOutlineLoopIcon,
  "download-off-twotone": Icons.DownloadOffTwotoneIcon,
  "download-off-twotone-loop": Icons.DownloadOffTwotoneLoopIcon,
  "download-outline": Icons.DownloadOutlineIcon,
  "download-outline-loop": Icons.DownloadOutlineLoopIcon,
  "download-twotone": Icons.DownloadTwotoneIcon,
  "download-twotone-loop": Icons.DownloadTwotoneLoopIcon,
  downloading: Icons.DownloadingIcon,
  "downloading-loop": Icons.DownloadingLoopIcon,
  edit: Icons.EditIcon,
  "edit-filled": Icons.EditFilledIcon,
  "edit-full-filled": Icons.EditFullFilledIcon,
  "edit-full-twotone": Icons.EditFullTwotoneIcon,
  "edit-twotone": Icons.EditTwotoneIcon,
  email: Icons.EmailIcon,
  "email-alert": Icons.EmailAlertIcon,
  "email-alert-filled": Icons.EmailAlertFilledIcon,
  "email-alert-twotone": Icons.EmailAlertTwotoneIcon,
  "email-alt-filled": Icons.EmailAltFilledIcon,
  "email-alt-twotone": Icons.EmailAltTwotoneIcon,
  "email-arrow-down": Icons.EmailArrowDownIcon,
  "email-arrow-down-filled": Icons.EmailArrowDownFilledIcon,
  "email-arrow-down-twotone": Icons.EmailArrowDownTwotoneIcon,
  "email-arrow-left": Icons.EmailArrowLeftIcon,
  "email-arrow-left-filled": Icons.EmailArrowLeftFilledIcon,
  "email-arrow-left-twotone": Icons.EmailArrowLeftTwotoneIcon,
  "email-arrow-right": Icons.EmailArrowRightIcon,
  "email-arrow-right-filled": Icons.EmailArrowRightFilledIcon,
  "email-arrow-right-twotone": Icons.EmailArrowRightTwotoneIcon,
  "email-arrow-up": Icons.EmailArrowUpIcon,
  "email-arrow-up-filled": Icons.EmailArrowUpFilledIcon,
  "email-arrow-up-twotone": Icons.EmailArrowUpTwotoneIcon,
  "email-check": Icons.EmailCheckIcon,
  "email-check-filled": Icons.EmailCheckFilledIcon,
  "email-check-twotone": Icons.EmailCheckTwotoneIcon,
  "email-filled": Icons.EmailFilledIcon,
  "email-minus": Icons.EmailMinusIcon,
  "email-minus-filled": Icons.EmailMinusFilledIcon,
  "email-minus-twotone": Icons.EmailMinusTwotoneIcon,
  "email-multiple": Icons.EmailMultipleIcon,
  "email-multiple-filled": Icons.EmailMultipleFilledIcon,
  "email-multiple-twotone": Icons.EmailMultipleTwotoneIcon,
  "email-opened": Icons.EmailOpenedIcon,
  "email-opened-alt-filled": Icons.EmailOpenedAltFilledIcon,
  "email-opened-alt-twotone": Icons.EmailOpenedAltTwotoneIcon,
  "email-opened-filled": Icons.EmailOpenedFilledIcon,
  "email-opened-multiple": Icons.EmailOpenedMultipleIcon,
  "email-opened-multiple-filled": Icons.EmailOpenedMultipleFilledIcon,
  "email-opened-multiple-twotone": Icons.EmailOpenedMultipleTwotoneIcon,
  "email-opened-twotone": Icons.EmailOpenedTwotoneIcon,
  "email-plus": Icons.EmailPlusIcon,
  "email-plus-filled": Icons.EmailPlusFilledIcon,
  "email-plus-twotone": Icons.EmailPlusTwotoneIcon,
  "email-remove": Icons.EmailRemoveIcon,
  "email-remove-filled": Icons.EmailRemoveFilledIcon,
  "email-remove-twotone": Icons.EmailRemoveTwotoneIcon,
  "email-twotone": Icons.EmailTwotoneIcon,
  "emoji-angry": Icons.EmojiAngryIcon,
  "emoji-angry-filled": Icons.EmojiAngryFilledIcon,
  "emoji-angry-twotone": Icons.EmojiAngryTwotoneIcon,
  "emoji-cry": Icons.EmojiCryIcon,
  "emoji-cry-filled": Icons.EmojiCryFilledIcon,
  "emoji-frown": Icons.EmojiFrownIcon,
  "emoji-frown-filled": Icons.EmojiFrownFilledIcon,
  "emoji-frown-open": Icons.EmojiFrownOpenIcon,
  "emoji-frown-open-filled": Icons.EmojiFrownOpenFilledIcon,
  "emoji-frown-open-twotone": Icons.EmojiFrownOpenTwotoneIcon,
  "emoji-frown-twotone": Icons.EmojiFrownTwotoneIcon,
  "emoji-grin": Icons.EmojiGrinIcon,
  "emoji-grin-filled": Icons.EmojiGrinFilledIcon,
  "emoji-grin-twotone": Icons.EmojiGrinTwotoneIcon,
  "emoji-neutral": Icons.EmojiNeutralIcon,
  "emoji-neutral-filled": Icons.EmojiNeutralFilledIcon,
  "emoji-neutral-twotone": Icons.EmojiNeutralTwotoneIcon,
  "emoji-smile": Icons.EmojiSmileIcon,
  "emoji-smile-filled": Icons.EmojiSmileFilledIcon,
  "emoji-smile-twotone": Icons.EmojiSmileTwotoneIcon,
  "emoji-smile-wink": Icons.EmojiSmileWinkIcon,
  "emoji-smile-wink-filled": Icons.EmojiSmileWinkFilledIcon,
  "emoji-smile-wink-twotone": Icons.EmojiSmileWinkTwotoneIcon,
  engine: Icons.EngineIcon,
  "engine-filled": Icons.EngineFilledIcon,
  "engine-off": Icons.EngineOffIcon,
  "engine-off-filled": Icons.EngineOffFilledIcon,
  "engine-off-twotone": Icons.EngineOffTwotoneIcon,
  "engine-twotone": Icons.EngineTwotoneIcon,
  "external-link": Icons.ExternalLinkIcon,
  "external-link-rounded": Icons.ExternalLinkRoundedIcon,
  facebook: Icons.FacebookIcon,
  file: Icons.FileIcon,
  "file-cancel": Icons.FileCancelIcon,
  "file-cancel-filled": Icons.FileCancelFilledIcon,
  "file-cancel-twotone": Icons.FileCancelTwotoneIcon,
  "file-document": Icons.FileDocumentIcon,
  "file-document-cancel": Icons.FileDocumentCancelIcon,
  "file-document-cancel-filled": Icons.FileDocumentCancelFilledIcon,
  "file-document-cancel-twotone": Icons.FileDocumentCancelTwotoneIcon,
  "file-document-filled": Icons.FileDocumentFilledIcon,
  "file-document-minus": Icons.FileDocumentMinusIcon,
  "file-document-minus-filled": Icons.FileDocumentMinusFilledIcon,
  "file-document-minus-twotone": Icons.FileDocumentMinusTwotoneIcon,
  "file-document-off": Icons.FileDocumentOffIcon,
  "file-document-off-filled": Icons.FileDocumentOffFilledIcon,
  "file-document-off-twotone": Icons.FileDocumentOffTwotoneIcon,
  "file-document-plus": Icons.FileDocumentPlusIcon,
  "file-document-plus-filled": Icons.FileDocumentPlusFilledIcon,
  "file-document-plus-twotone": Icons.FileDocumentPlusTwotoneIcon,
  "file-document-remove": Icons.FileDocumentRemoveIcon,
  "file-document-remove-filled": Icons.FileDocumentRemoveFilledIcon,
  "file-document-remove-twotone": Icons.FileDocumentRemoveTwotoneIcon,
  "file-document-twotone": Icons.FileDocumentTwotoneIcon,
  "file-download": Icons.FileDownloadIcon,
  "file-download-filled": Icons.FileDownloadFilledIcon,
  "file-download-twotone": Icons.FileDownloadTwotoneIcon,
  "file-export": Icons.FileExportIcon,
  "file-export-filled": Icons.FileExportFilledIcon,
  "file-export-twotone": Icons.FileExportTwotoneIcon,
  "file-filled": Icons.FileFilledIcon,
  "file-import": Icons.FileImportIcon,
  "file-import-filled": Icons.FileImportFilledIcon,
  "file-import-twotone": Icons.FileImportTwotoneIcon,
  "file-minus": Icons.FileMinusIcon,
  "file-minus-filled": Icons.FileMinusFilledIcon,
  "file-minus-twotone": Icons.FileMinusTwotoneIcon,
  "file-off": Icons.FileOffIcon,
  "file-off-filled": Icons.FileOffFilledIcon,
  "file-off-twotone": Icons.FileOffTwotoneIcon,
  "file-plus": Icons.FilePlusIcon,
  "file-plus-filled": Icons.FilePlusFilledIcon,
  "file-plus-twotone": Icons.FilePlusTwotoneIcon,
  "file-remove": Icons.FileRemoveIcon,
  "file-remove-filled": Icons.FileRemoveFilledIcon,
  "file-remove-twotone": Icons.FileRemoveTwotoneIcon,
  "file-search": Icons.FileSearchIcon,
  "file-search-filled": Icons.FileSearchFilledIcon,
  "file-search-twotone": Icons.FileSearchTwotoneIcon,
  "file-twotone": Icons.FileTwotoneIcon,
  "file-upload": Icons.FileUploadIcon,
  "file-upload-filled": Icons.FileUploadFilledIcon,
  "file-upload-twotone": Icons.FileUploadTwotoneIcon,
  filter: Icons.FilterIcon,
  "filter-alt": Icons.FilterAltIcon,
  "filter-alt-off": Icons.FilterAltOffIcon,
  "filter-confirm": Icons.FilterConfirmIcon,
  "filter-confirm-filled": Icons.FilterConfirmFilledIcon,
  "filter-confirm-twotone": Icons.FilterConfirmTwotoneIcon,
  "filter-filled": Icons.FilterFilledIcon,
  "filter-minus": Icons.FilterMinusIcon,
  "filter-minus-filled": Icons.FilterMinusFilledIcon,
  "filter-minus-twotone": Icons.FilterMinusTwotoneIcon,
  "filter-off": Icons.FilterOffIcon,
  "filter-off-filled": Icons.FilterOffFilledIcon,
  "filter-off-twotone": Icons.FilterOffTwotoneIcon,
  "filter-plus": Icons.FilterPlusIcon,
  "filter-plus-filled": Icons.FilterPlusFilledIcon,
  "filter-plus-twotone": Icons.FilterPlusTwotoneIcon,
  "filter-remove": Icons.FilterRemoveIcon,
  "filter-remove-filled": Icons.FilterRemoveFilledIcon,
  "filter-remove-twotone": Icons.FilterRemoveTwotoneIcon,
  "filter-twotone": Icons.FilterTwotoneIcon,
  folder: Icons.FolderIcon,
  "folder-arrow-down": Icons.FolderArrowDownIcon,
  "folder-arrow-down-filled": Icons.FolderArrowDownFilledIcon,
  "folder-arrow-down-twotone": Icons.FolderArrowDownTwotoneIcon,
  "folder-arrow-left": Icons.FolderArrowLeftIcon,
  "folder-arrow-left-filled": Icons.FolderArrowLeftFilledIcon,
  "folder-arrow-left-twotone": Icons.FolderArrowLeftTwotoneIcon,
  "folder-arrow-right": Icons.FolderArrowRightIcon,
  "folder-arrow-right-filled": Icons.FolderArrowRightFilledIcon,
  "folder-arrow-right-twotone": Icons.FolderArrowRightTwotoneIcon,
  "folder-arrow-up": Icons.FolderArrowUpIcon,
  "folder-arrow-up-filled": Icons.FolderArrowUpFilledIcon,
  "folder-arrow-up-twotone": Icons.FolderArrowUpTwotoneIcon,
  "folder-cancel": Icons.FolderCancelIcon,
  "folder-cancel-filled": Icons.FolderCancelFilledIcon,
  "folder-cancel-twotone": Icons.FolderCancelTwotoneIcon,
  "folder-check": Icons.FolderCheckIcon,
  "folder-check-filled": Icons.FolderCheckFilledIcon,
  "folder-check-twotone": Icons.FolderCheckTwotoneIcon,
  "folder-filled": Icons.FolderFilledIcon,
  "folder-minus": Icons.FolderMinusIcon,
  "folder-minus-filled": Icons.FolderMinusFilledIcon,
  "folder-minus-twotone": Icons.FolderMinusTwotoneIcon,
  "folder-multiple": Icons.FolderMultipleIcon,
  "folder-multiple-filled": Icons.FolderMultipleFilledIcon,
  "folder-multiple-twotone": Icons.FolderMultipleTwotoneIcon,
  "folder-music": Icons.FolderMusicIcon,
  "folder-music-filled": Icons.FolderMusicFilledIcon,
  "folder-music-twotone": Icons.FolderMusicTwotoneIcon,
  "folder-network": Icons.FolderNetworkIcon,
  "folder-network-filled": Icons.FolderNetworkFilledIcon,
  "folder-network-twotone": Icons.FolderNetworkTwotoneIcon,
  "folder-off": Icons.FolderOffIcon,
  "folder-off-filled": Icons.FolderOffFilledIcon,
  "folder-off-twotone": Icons.FolderOffTwotoneIcon,
  "folder-plus": Icons.FolderPlusIcon,
  "folder-plus-filled": Icons.FolderPlusFilledIcon,
  "folder-plus-twotone": Icons.FolderPlusTwotoneIcon,
  "folder-remove": Icons.FolderRemoveIcon,
  "folder-remove-filled": Icons.FolderRemoveFilledIcon,
  "folder-remove-twotone": Icons.FolderRemoveTwotoneIcon,
  "folder-settings": Icons.FolderSettingsIcon,
  "folder-settings-filled": Icons.FolderSettingsFilledIcon,
  "folder-settings-twotone": Icons.FolderSettingsTwotoneIcon,
  "folder-twotone": Icons.FolderTwotoneIcon,
  "folder-zip": Icons.FolderZipIcon,
  "folder-zip-filled": Icons.FolderZipFilledIcon,
  "folder-zip-twotone": Icons.FolderZipTwotoneIcon,
  "fork-left": Icons.ForkLeftIcon,
  "fork-right": Icons.ForkRightIcon,
  gauge: Icons.GaugeIcon,
  "gauge-empty": Icons.GaugeEmptyIcon,
  "gauge-empty-twotone": Icons.GaugeEmptyTwotoneIcon,
  "gauge-full": Icons.GaugeFullIcon,
  "gauge-full-twotone": Icons.GaugeFullTwotoneIcon,
  "gauge-loop": Icons.GaugeLoopIcon,
  "gauge-low": Icons.GaugeLowIcon,
  "gauge-low-twotone": Icons.GaugeLowTwotoneIcon,
  "gauge-twotone": Icons.GaugeTwotoneIcon,
  "gauge-twotone-loop": Icons.GaugeTwotoneLoopIcon,
  github: Icons.GithubIcon,
  "github-loop": Icons.GithubLoopIcon,
  "github-twotone": Icons.GithubTwotoneIcon,
  "github-twotone-loop": Icons.GithubTwotoneLoopIcon,
  "grid-3": Icons.Grid3Icon,
  "grid-3-filled": Icons.Grid3FilledIcon,
  "grid-3-twotone": Icons.Grid3TwotoneIcon,
  hash: Icons.HashIcon,
  "hash-small": Icons.HashSmallIcon,
  "hazard-lights": Icons.HazardLightsIcon,
  "hazard-lights-filled": Icons.HazardLightsFilledIcon,
  "hazard-lights-filled-loop": Icons.HazardLightsFilledLoopIcon,
  "hazard-lights-loop": Icons.HazardLightsLoopIcon,
  "hazard-lights-off": Icons.HazardLightsOffIcon,
  "hazard-lights-off-filled": Icons.HazardLightsOffFilledIcon,
  "hazard-lights-off-filled-loop": Icons.HazardLightsOffFilledLoopIcon,
  "hazard-lights-off-loop": Icons.HazardLightsOffLoopIcon,
  "hazard-lights-off-twotone": Icons.HazardLightsOffTwotoneIcon,
  "hazard-lights-off-twotone-loop": Icons.HazardLightsOffTwotoneLoopIcon,
  "hazard-lights-twotone": Icons.HazardLightsTwotoneIcon,
  "hazard-lights-twotone-loop": Icons.HazardLightsTwotoneLoopIcon,
  heart: Icons.HeartIcon,
  "heart-filled": Icons.HeartFilledIcon,
  "heart-filled-half": Icons.HeartFilledHalfIcon,
  "heart-half": Icons.HeartHalfIcon,
  "heart-half-filled": Icons.HeartHalfFilledIcon,
  "heart-half-twotone": Icons.HeartHalfTwotoneIcon,
  "heart-twotone": Icons.HeartTwotoneIcon,
  "heart-twotone-half": Icons.HeartTwotoneHalfIcon,
  "heart-twotone-half-filled": Icons.HeartTwotoneHalfFilledIcon,
  home: Icons.HomeIcon,
  "home-alt-twotone": Icons.HomeAltTwotoneIcon,
  "home-md": Icons.HomeMdIcon,
  "home-md-alt-twotone": Icons.HomeMdAltTwotoneIcon,
  "home-md-twotone": Icons.HomeMdTwotoneIcon,
  "home-simple": Icons.HomeSimpleIcon,
  "home-simple-filled": Icons.HomeSimpleFilledIcon,
  "home-simple-twotone": Icons.HomeSimpleTwotoneIcon,
  "home-twotone": Icons.HomeTwotoneIcon,
  iconify1: Icons.Iconify1Icon,
  iconify2: Icons.Iconify2Icon,
  "iconify2-static": Icons.Iconify2StaticIcon,
  "iconify2-static-twotone": Icons.Iconify2StaticTwotoneIcon,
  "iconify2-twotone": Icons.Iconify2TwotoneIcon,
  image: Icons.ImageIcon,
  "image-filled": Icons.ImageFilledIcon,
  "image-twotone": Icons.ImageTwotoneIcon,
  instagram: Icons.InstagramIcon,
  laptop: Icons.LaptopIcon,
  "laptop-filled": Icons.LaptopFilledIcon,
  "laptop-off": Icons.LaptopOffIcon,
  "laptop-off-filled": Icons.LaptopOffFilledIcon,
  "laptop-off-twotone": Icons.LaptopOffTwotoneIcon,
  "laptop-twotone": Icons.LaptopTwotoneIcon,
  "light-dark": Icons.LightDarkIcon,
  "light-dark-loop": Icons.LightDarkLoopIcon,
  lightbulb: Icons.LightbulbIcon,
  "lightbulb-filled": Icons.LightbulbFilledIcon,
  "lightbulb-off": Icons.LightbulbOffIcon,
  "lightbulb-off-filled": Icons.LightbulbOffFilledIcon,
  "lightbulb-off-filled-loop": Icons.LightbulbOffFilledLoopIcon,
  "lightbulb-off-loop": Icons.LightbulbOffLoopIcon,
  "lightbulb-off-twotone": Icons.LightbulbOffTwotoneIcon,
  "lightbulb-off-twotone-loop": Icons.LightbulbOffTwotoneLoopIcon,
  "lightbulb-twotone": Icons.LightbulbTwotoneIcon,
  link: Icons.LinkIcon,
  linkedin: Icons.LinkedinIcon,
  list: Icons.ListIcon,
  "list-3": Icons.List3Icon,
  "list-3-filled": Icons.List3FilledIcon,
  "list-3-twotone": Icons.List3TwotoneIcon,
  "list-indented": Icons.ListIndentedIcon,
  "list-indented-reversed": Icons.ListIndentedReversedIcon,
  "loading-alt-loop": Icons.LoadingAltLoopIcon,
  "loading-loop": Icons.LoadingLoopIcon,
  "loading-twotone-loop": Icons.LoadingTwotoneLoopIcon,
  "log-in": Icons.LogInIcon,
  "log-out": Icons.LogOutIcon,
  login: Icons.LoginIcon,
  logout: Icons.LogoutIcon,
  "map-marker": Icons.MapMarkerIcon,
  "map-marker-alt": Icons.MapMarkerAltIcon,
  "map-marker-alt-filled": Icons.MapMarkerAltFilledIcon,
  "map-marker-alt-filled-loop": Icons.MapMarkerAltFilledLoopIcon,
  "map-marker-alt-loop": Icons.MapMarkerAltLoopIcon,
  "map-marker-alt-off": Icons.MapMarkerAltOffIcon,
  "map-marker-alt-off-filled": Icons.MapMarkerAltOffFilledIcon,
  "map-marker-alt-off-filled-loop": Icons.MapMarkerAltOffFilledLoopIcon,
  "map-marker-alt-off-loop": Icons.MapMarkerAltOffLoopIcon,
  "map-marker-alt-off-twotone": Icons.MapMarkerAltOffTwotoneIcon,
  "map-marker-alt-off-twotone-loop": Icons.MapMarkerAltOffTwotoneLoopIcon,
  "map-marker-alt-twotone": Icons.MapMarkerAltTwotoneIcon,
  "map-marker-alt-twotone-loop": Icons.MapMarkerAltTwotoneLoopIcon,
  "map-marker-filled": Icons.MapMarkerFilledIcon,
  "map-marker-filled-loop": Icons.MapMarkerFilledLoopIcon,
  "map-marker-loop": Icons.MapMarkerLoopIcon,
  "map-marker-minus": Icons.MapMarkerMinusIcon,
  "map-marker-minus-filled": Icons.MapMarkerMinusFilledIcon,
  "map-marker-minus-twotone": Icons.MapMarkerMinusTwotoneIcon,
  "map-marker-multiple": Icons.MapMarkerMultipleIcon,
  "map-marker-multiple-alt": Icons.MapMarkerMultipleAltIcon,
  "map-marker-multiple-alt-filled": Icons.MapMarkerMultipleAltFilledIcon,
  "map-marker-multiple-alt-filled-loop":
    Icons.MapMarkerMultipleAltFilledLoopIcon,
  "map-marker-multiple-alt-loop": Icons.MapMarkerMultipleAltLoopIcon,
  "map-marker-multiple-alt-off": Icons.MapMarkerMultipleAltOffIcon,
  "map-marker-multiple-alt-off-filled": Icons.MapMarkerMultipleAltOffFilledIcon,
  "map-marker-multiple-alt-off-filled-loop":
    Icons.MapMarkerMultipleAltOffFilledLoopIcon,
  "map-marker-multiple-alt-off-loop": Icons.MapMarkerMultipleAltOffLoopIcon,
  "map-marker-multiple-alt-off-twotone":
    Icons.MapMarkerMultipleAltOffTwotoneIcon,
  "map-marker-multiple-alt-off-twotone-loop":
    Icons.MapMarkerMultipleAltOffTwotoneLoopIcon,
  "map-marker-multiple-alt-twotone": Icons.MapMarkerMultipleAltTwotoneIcon,
  "map-marker-multiple-alt-twotone-loop":
    Icons.MapMarkerMultipleAltTwotoneLoopIcon,
  "map-marker-multiple-filled": Icons.MapMarkerMultipleFilledIcon,
  "map-marker-multiple-filled-loop": Icons.MapMarkerMultipleFilledLoopIcon,
  "map-marker-multiple-loop": Icons.MapMarkerMultipleLoopIcon,
  "map-marker-multiple-off": Icons.MapMarkerMultipleOffIcon,
  "map-marker-multiple-off-filled": Icons.MapMarkerMultipleOffFilledIcon,
  "map-marker-multiple-off-filled-loop":
    Icons.MapMarkerMultipleOffFilledLoopIcon,
  "map-marker-multiple-off-loop": Icons.MapMarkerMultipleOffLoopIcon,
  "map-marker-multiple-off-twotone": Icons.MapMarkerMultipleOffTwotoneIcon,
  "map-marker-multiple-off-twotone-loop":
    Icons.MapMarkerMultipleOffTwotoneLoopIcon,
  "map-marker-multiple-twotone": Icons.MapMarkerMultipleTwotoneIcon,
  "map-marker-multiple-twotone-loop": Icons.MapMarkerMultipleTwotoneLoopIcon,
  "map-marker-off": Icons.MapMarkerOffIcon,
  "map-marker-off-filled": Icons.MapMarkerOffFilledIcon,
  "map-marker-off-filled-loop": Icons.MapMarkerOffFilledLoopIcon,
  "map-marker-off-loop": Icons.MapMarkerOffLoopIcon,
  "map-marker-off-twotone": Icons.MapMarkerOffTwotoneIcon,
  "map-marker-off-twotone-loop": Icons.MapMarkerOffTwotoneLoopIcon,
  "map-marker-plus": Icons.MapMarkerPlusIcon,
  "map-marker-plus-filled": Icons.MapMarkerPlusFilledIcon,
  "map-marker-plus-twotone": Icons.MapMarkerPlusTwotoneIcon,
  "map-marker-radius": Icons.MapMarkerRadiusIcon,
  "map-marker-radius-filled": Icons.MapMarkerRadiusFilledIcon,
  "map-marker-radius-twotone": Icons.MapMarkerRadiusTwotoneIcon,
  "map-marker-remove": Icons.MapMarkerRemoveIcon,
  "map-marker-remove-filled": Icons.MapMarkerRemoveFilledIcon,
  "map-marker-remove-twotone": Icons.MapMarkerRemoveTwotoneIcon,
  "map-marker-twotone": Icons.MapMarkerTwotoneIcon,
  "map-marker-twotone-loop": Icons.MapMarkerTwotoneLoopIcon,
  marker: Icons.MarkerIcon,
  "marker-filled": Icons.MarkerFilledIcon,
  "marker-twotone": Icons.MarkerTwotoneIcon,
  mastodon: Icons.MastodonIcon,
  "mastodon-filled": Icons.MastodonFilledIcon,
  "mastodon-twotone": Icons.MastodonTwotoneIcon,
  "medical-services": Icons.MedicalServicesIcon,
  "medical-services-filled": Icons.MedicalServicesFilledIcon,
  "medical-services-twotone": Icons.MedicalServicesTwotoneIcon,
  menu: Icons.MenuIcon,
  "menu-fold-left": Icons.MenuFoldLeftIcon,
  "menu-fold-right": Icons.MenuFoldRightIcon,
  "menu-to-close-alt-transition": Icons.MenuToCloseAltTransitionIcon,
  "menu-to-close-transition": Icons.MenuToCloseTransitionIcon,
  "menu-unfold-left": Icons.MenuUnfoldLeftIcon,
  "menu-unfold-right": Icons.MenuUnfoldRightIcon,
  minus: Icons.MinusIcon,
  "minus-circle": Icons.MinusCircleIcon,
  "minus-circle-filled": Icons.MinusCircleFilledIcon,
  "minus-circle-twotone": Icons.MinusCircleTwotoneIcon,
  "minus-square": Icons.MinusSquareIcon,
  "minus-square-filled": Icons.MinusSquareFilledIcon,
  "minus-square-twotone": Icons.MinusSquareTwotoneIcon,
  monitor: Icons.MonitorIcon,
  "monitor-arrow-down": Icons.MonitorArrowDownIcon,
  "monitor-arrow-down-filled": Icons.MonitorArrowDownFilledIcon,
  "monitor-arrow-down-twotone": Icons.MonitorArrowDownTwotoneIcon,
  "monitor-arrow-up": Icons.MonitorArrowUpIcon,
  "monitor-arrow-up-filled": Icons.MonitorArrowUpFilledIcon,
  "monitor-arrow-up-twotone": Icons.MonitorArrowUpTwotoneIcon,
  "monitor-filled": Icons.MonitorFilledIcon,
  "monitor-mutlple": Icons.MonitorMutlpleIcon,
  "monitor-mutlple-filled": Icons.MonitorMutlpleFilledIcon,
  "monitor-mutlple-twotone": Icons.MonitorMutlpleTwotoneIcon,
  "monitor-off": Icons.MonitorOffIcon,
  "monitor-off-filled": Icons.MonitorOffFilledIcon,
  "monitor-off-twotone": Icons.MonitorOffTwotoneIcon,
  "monitor-screenshot": Icons.MonitorScreenshotIcon,
  "monitor-screenshot-filled": Icons.MonitorScreenshotFilledIcon,
  "monitor-screenshot-twotone": Icons.MonitorScreenshotTwotoneIcon,
  "monitor-small": Icons.MonitorSmallIcon,
  "monitor-small-filled": Icons.MonitorSmallFilledIcon,
  "monitor-small-off": Icons.MonitorSmallOffIcon,
  "monitor-small-off-filled": Icons.MonitorSmallOffFilledIcon,
  "monitor-small-off-twotone": Icons.MonitorSmallOffTwotoneIcon,
  "monitor-small-twotone": Icons.MonitorSmallTwotoneIcon,
  "monitor-twotone": Icons.MonitorTwotoneIcon,
  moon: Icons.MoonIcon,
  "moon-alt": Icons.MoonAltIcon,
  "moon-alt-filled": Icons.MoonAltFilledIcon,
  "moon-alt-filled-loop": Icons.MoonAltFilledLoopIcon,
  "moon-alt-loop": Icons.MoonAltLoopIcon,
  "moon-alt-off": Icons.MoonAltOffIcon,
  "moon-alt-off-filled": Icons.MoonAltOffFilledIcon,
  "moon-alt-off-filled-loop": Icons.MoonAltOffFilledLoopIcon,
  "moon-alt-off-loop": Icons.MoonAltOffLoopIcon,
  "moon-alt-off-twotone": Icons.MoonAltOffTwotoneIcon,
  "moon-alt-off-twotone-loop": Icons.MoonAltOffTwotoneLoopIcon,
  "moon-alt-to-sunny-outline-loop-transition":
    Icons.MoonAltToSunnyOutlineLoopTransitionIcon,
  "moon-alt-twotone": Icons.MoonAltTwotoneIcon,
  "moon-alt-twotone-loop": Icons.MoonAltTwotoneLoopIcon,
  "moon-filled": Icons.MoonFilledIcon,
  "moon-filled-alt-loop": Icons.MoonFilledAltLoopIcon,
  "moon-filled-alt-to-sunny-filled-loop-transition":
    Icons.MoonFilledAltToSunnyFilledLoopTransitionIcon,
  "moon-filled-loop": Icons.MoonFilledLoopIcon,
  "moon-filled-to-sunny-filled-loop-transition":
    Icons.MoonFilledToSunnyFilledLoopTransitionIcon,
  "moon-filled-to-sunny-filled-transition":
    Icons.MoonFilledToSunnyFilledTransitionIcon,
  "moon-loop": Icons.MoonLoopIcon,
  "moon-off": Icons.MoonOffIcon,
  "moon-off-filled": Icons.MoonOffFilledIcon,
  "moon-off-filled-loop": Icons.MoonOffFilledLoopIcon,
  "moon-off-loop": Icons.MoonOffLoopIcon,
  "moon-off-twotone": Icons.MoonOffTwotoneIcon,
  "moon-off-twotone-loop": Icons.MoonOffTwotoneLoopIcon,
  "moon-rising": Icons.MoonRisingIcon,
  "moon-rising-alt": Icons.MoonRisingAltIcon,
  "moon-rising-alt-filled": Icons.MoonRisingAltFilledIcon,
  "moon-rising-alt-filled-loop": Icons.MoonRisingAltFilledLoopIcon,
  "moon-rising-alt-loop": Icons.MoonRisingAltLoopIcon,
  "moon-rising-alt-twotone": Icons.MoonRisingAltTwotoneIcon,
  "moon-rising-alt-twotone-loop": Icons.MoonRisingAltTwotoneLoopIcon,
  "moon-rising-filled": Icons.MoonRisingFilledIcon,
  "moon-rising-filled-alt-loop": Icons.MoonRisingFilledAltLoopIcon,
  "moon-rising-filled-loop": Icons.MoonRisingFilledLoopIcon,
  "moon-rising-loop": Icons.MoonRisingLoopIcon,
  "moon-rising-twotone": Icons.MoonRisingTwotoneIcon,
  "moon-rising-twotone-alt-loop": Icons.MoonRisingTwotoneAltLoopIcon,
  "moon-rising-twotone-loop": Icons.MoonRisingTwotoneLoopIcon,
  "moon-simple": Icons.MoonSimpleIcon,
  "moon-simple-filled": Icons.MoonSimpleFilledIcon,
  "moon-simple-off": Icons.MoonSimpleOffIcon,
  "moon-simple-off-filled": Icons.MoonSimpleOffFilledIcon,
  "moon-simple-off-twotone": Icons.MoonSimpleOffTwotoneIcon,
  "moon-simple-twotone": Icons.MoonSimpleTwotoneIcon,
  "moon-to-sunny-outline-loop-transition":
    Icons.MoonToSunnyOutlineLoopTransitionIcon,
  "moon-to-sunny-outline-transition": Icons.MoonToSunnyOutlineTransitionIcon,
  "moon-twotone": Icons.MoonTwotoneIcon,
  "moon-twotone-alt-loop": Icons.MoonTwotoneAltLoopIcon,
  "moon-twotone-loop": Icons.MoonTwotoneLoopIcon,
  mushroom: Icons.MushroomIcon,
  "mushroom-filled": Icons.MushroomFilledIcon,
  "mushroom-off": Icons.MushroomOffIcon,
  "mushroom-off-filled": Icons.MushroomOffFilledIcon,
  "mushroom-off-twotone": Icons.MushroomOffTwotoneIcon,
  "mushroom-twotone": Icons.MushroomTwotoneIcon,
  "my-location": Icons.MyLocationIcon,
  "my-location-loop": Icons.MyLocationLoopIcon,
  "my-location-off": Icons.MyLocationOffIcon,
  "my-location-off-loop": Icons.MyLocationOffLoopIcon,
  "my-location-off-twotone": Icons.MyLocationOffTwotoneIcon,
  "my-location-off-twotone-loop": Icons.MyLocationOffTwotoneLoopIcon,
  "my-location-twotone": Icons.MyLocationTwotoneIcon,
  "my-location-twotone-loop": Icons.MyLocationTwotoneLoopIcon,
  "navigation-left-down": Icons.NavigationLeftDownIcon,
  "navigation-left-up": Icons.NavigationLeftUpIcon,
  "navigation-right-down": Icons.NavigationRightDownIcon,
  "navigation-right-up": Icons.NavigationRightUpIcon,
  "paint-drop": Icons.PaintDropIcon,
  "paint-drop-filled": Icons.PaintDropFilledIcon,
  "paint-drop-half-filled": Icons.PaintDropHalfFilledIcon,
  "paint-drop-half-filled-twotone": Icons.PaintDropHalfFilledTwotoneIcon,
  "paint-drop-half-twotone": Icons.PaintDropHalfTwotoneIcon,
  "paint-drop-twotone": Icons.PaintDropTwotoneIcon,
  patreon: Icons.PatreonIcon,
  pause: Icons.PauseIcon,
  "pause-off": Icons.PauseOffIcon,
  "pause-to-play-filled-transition": Icons.PauseToPlayFilledTransitionIcon,
  "pause-to-play-transition": Icons.PauseToPlayTransitionIcon,
  peanut: Icons.PeanutIcon,
  "peanut-filled": Icons.PeanutFilledIcon,
  "peanut-off": Icons.PeanutOffIcon,
  "peanut-off-filled": Icons.PeanutOffFilledIcon,
  "peanut-off-twotone": Icons.PeanutOffTwotoneIcon,
  "peanut-twotone": Icons.PeanutTwotoneIcon,
  peertube: Icons.PeertubeIcon,
  "peertube-alt": Icons.PeertubeAltIcon,
  pencil: Icons.PencilIcon,
  "pencil-alt-twotone": Icons.PencilAltTwotoneIcon,
  "pencil-twotone": Icons.PencilTwotoneIcon,
  person: Icons.PersonIcon,
  "person-add": Icons.PersonAddIcon,
  "person-add-filled": Icons.PersonAddFilledIcon,
  "person-add-twotone": Icons.PersonAddTwotoneIcon,
  "person-filled": Icons.PersonFilledIcon,
  "person-off": Icons.PersonOffIcon,
  "person-off-filled": Icons.PersonOffFilledIcon,
  "person-off-filled-loop": Icons.PersonOffFilledLoopIcon,
  "person-off-loop": Icons.PersonOffLoopIcon,
  "person-off-twotone": Icons.PersonOffTwotoneIcon,
  "person-off-twotone-loop": Icons.PersonOffTwotoneLoopIcon,
  "person-remove": Icons.PersonRemoveIcon,
  "person-remove-filled": Icons.PersonRemoveFilledIcon,
  "person-remove-twotone": Icons.PersonRemoveTwotoneIcon,
  "person-search": Icons.PersonSearchIcon,
  "person-search-filled": Icons.PersonSearchFilledIcon,
  "person-search-twotone": Icons.PersonSearchTwotoneIcon,
  "person-twotone": Icons.PersonTwotoneIcon,
  phone: Icons.PhoneIcon,
  "phone-add": Icons.PhoneAddIcon,
  "phone-add-filled": Icons.PhoneAddFilledIcon,
  "phone-add-twotone": Icons.PhoneAddTwotoneIcon,
  "phone-call": Icons.PhoneCallIcon,
  "phone-call-filled": Icons.PhoneCallFilledIcon,
  "phone-call-filled-loop": Icons.PhoneCallFilledLoopIcon,
  "phone-call-loop": Icons.PhoneCallLoopIcon,
  "phone-call-twotone": Icons.PhoneCallTwotoneIcon,
  "phone-call-twotone-loop": Icons.PhoneCallTwotoneLoopIcon,
  "phone-filled": Icons.PhoneFilledIcon,
  "phone-filled-loop": Icons.PhoneFilledLoopIcon,
  "phone-incoming": Icons.PhoneIncomingIcon,
  "phone-incoming-filled": Icons.PhoneIncomingFilledIcon,
  "phone-incoming-twotone": Icons.PhoneIncomingTwotoneIcon,
  "phone-loop": Icons.PhoneLoopIcon,
  "phone-off": Icons.PhoneOffIcon,
  "phone-off-filled": Icons.PhoneOffFilledIcon,
  "phone-off-filled-loop": Icons.PhoneOffFilledLoopIcon,
  "phone-off-loop": Icons.PhoneOffLoopIcon,
  "phone-off-twotone": Icons.PhoneOffTwotoneIcon,
  "phone-off-twotone-loop": Icons.PhoneOffTwotoneLoopIcon,
  "phone-outgoing": Icons.PhoneOutgoingIcon,
  "phone-outgoing-filled": Icons.PhoneOutgoingFilledIcon,
  "phone-outgoing-twotone": Icons.PhoneOutgoingTwotoneIcon,
  "phone-remove": Icons.PhoneRemoveIcon,
  "phone-remove-filled": Icons.PhoneRemoveFilledIcon,
  "phone-remove-twotone": Icons.PhoneRemoveTwotoneIcon,
  "phone-twotone": Icons.PhoneTwotoneIcon,
  "phone-twotone-loop": Icons.PhoneTwotoneLoopIcon,
  pixelfed: Icons.PixelfedIcon,
  "pixelfed-filled": Icons.PixelfedFilledIcon,
  "pixelfed-twotone": Icons.PixelfedTwotoneIcon,
  pizza: Icons.PizzaIcon,
  "pizza-filled": Icons.PizzaFilledIcon,
  "pizza-off": Icons.PizzaOffIcon,
  "pizza-off-filled": Icons.PizzaOffFilledIcon,
  "pizza-off-twotone": Icons.PizzaOffTwotoneIcon,
  "pizza-twotone": Icons.PizzaTwotoneIcon,
  play: Icons.PlayIcon,
  "play-filled": Icons.PlayFilledIcon,
  "play-filled-to-pause-transition": Icons.PlayFilledToPauseTransitionIcon,
  "play-off": Icons.PlayOffIcon,
  "play-off-filled": Icons.PlayOffFilledIcon,
  "play-off-twotone": Icons.PlayOffTwotoneIcon,
  "play-to-pause-transition": Icons.PlayToPauseTransitionIcon,
  "play-twotone": Icons.PlayTwotoneIcon,
  pleroma: Icons.PleromaIcon,
  plus: Icons.PlusIcon,
  "plus-circle": Icons.PlusCircleIcon,
  "plus-circle-filled": Icons.PlusCircleFilledIcon,
  "plus-circle-twotone": Icons.PlusCircleTwotoneIcon,
  "plus-square": Icons.PlusSquareIcon,
  "plus-square-filled": Icons.PlusSquareFilledIcon,
  "plus-square-twotone": Icons.PlusSquareTwotoneIcon,
  question: Icons.QuestionIcon,
  "question-circle": Icons.QuestionCircleIcon,
  "question-circle-twotone": Icons.QuestionCircleTwotoneIcon,
  "question-square": Icons.QuestionSquareIcon,
  "question-square-twotone": Icons.QuestionSquareTwotoneIcon,
  reddit: Icons.RedditIcon,
  "reddit-circle": Icons.RedditCircleIcon,
  "reddit-circle-loop": Icons.RedditCircleLoopIcon,
  "reddit-loop": Icons.RedditLoopIcon,
  remove: Icons.RemoveIcon,
  "rotate-180": Icons.Rotate180Icon,
  "rotate-270": Icons.Rotate270Icon,
  "rotate-90": Icons.Rotate90Icon,
  "round-360": Icons.Round360Icon,
  "round-ramp-left": Icons.RoundRampLeftIcon,
  "round-ramp-right": Icons.RoundRampRightIcon,
  "roundabout-left": Icons.RoundaboutLeftIcon,
  "roundabout-right": Icons.RoundaboutRightIcon,
  rss: Icons.RssIcon,
  search: Icons.SearchIcon,
  "search-filled": Icons.SearchFilledIcon,
  "search-twotone": Icons.SearchTwotoneIcon,
  security: Icons.SecurityIcon,
  "security-filled": Icons.SecurityFilledIcon,
  "security-off": Icons.SecurityOffIcon,
  "security-off-filled": Icons.SecurityOffFilledIcon,
  "security-off-twotone": Icons.SecurityOffTwotoneIcon,
  "security-twotone": Icons.SecurityTwotoneIcon,
  soundcloud: Icons.SoundcloudIcon,
  speed: Icons.SpeedIcon,
  "speed-loop": Icons.SpeedLoopIcon,
  "speed-twotone": Icons.SpeedTwotoneIcon,
  "speed-twotone-loop": Icons.SpeedTwotoneLoopIcon,
  speedometer: Icons.SpeedometerIcon,
  "speedometer-loop": Icons.SpeedometerLoopIcon,
  spotify: Icons.SpotifyIcon,
  "spotify-filled": Icons.SpotifyFilledIcon,
  "spotify-twotone": Icons.SpotifyTwotoneIcon,
  square: Icons.SquareIcon,
  "square-filled": Icons.SquareFilledIcon,
  "square-filled-to-confirm-square-filled-transition":
    Icons.SquareFilledToConfirmSquareFilledTransitionIcon,
  "square-to-confirm-square-transition":
    Icons.SquareToConfirmSquareTransitionIcon,
  "square-to-confirm-square-twotone-transition":
    Icons.SquareToConfirmSquareTwotoneTransitionIcon,
  "square-twotone": Icons.SquareTwotoneIcon,
  "square-twotone-to-confirm-square-transition":
    Icons.SquareTwotoneToConfirmSquareTransitionIcon,
  "square-twotone-to-confirm-square-twotone-transition":
    Icons.SquareTwotoneToConfirmSquareTwotoneTransitionIcon,
  star: Icons.StarIcon,
  "star-alt": Icons.StarAltIcon,
  "star-alt-filled": Icons.StarAltFilledIcon,
  "star-alt-filled-half": Icons.StarAltFilledHalfIcon,
  "star-alt-filled-right-half": Icons.StarAltFilledRightHalfIcon,
  "star-alt-twotone": Icons.StarAltTwotoneIcon,
  "star-alt-twotone-half": Icons.StarAltTwotoneHalfIcon,
  "star-alt-twotone-right-half": Icons.StarAltTwotoneRightHalfIcon,
  "star-filled": Icons.StarFilledIcon,
  "star-filled-half": Icons.StarFilledHalfIcon,
  "star-filled-right-half": Icons.StarFilledRightHalfIcon,
  "star-half": Icons.StarHalfIcon,
  "star-half-alt": Icons.StarHalfAltIcon,
  "star-half-alt-filled": Icons.StarHalfAltFilledIcon,
  "star-half-alt-twotone": Icons.StarHalfAltTwotoneIcon,
  "star-half-filled": Icons.StarHalfFilledIcon,
  "star-half-twotone": Icons.StarHalfTwotoneIcon,
  "star-pulsating-filled-loop": Icons.StarPulsatingFilledLoopIcon,
  "star-pulsating-loop": Icons.StarPulsatingLoopIcon,
  "star-pulsating-twotone-loop": Icons.StarPulsatingTwotoneLoopIcon,
  "star-right-half": Icons.StarRightHalfIcon,
  "star-right-half-alt": Icons.StarRightHalfAltIcon,
  "star-right-half-alt-filled": Icons.StarRightHalfAltFilledIcon,
  "star-right-half-alt-twotone": Icons.StarRightHalfAltTwotoneIcon,
  "star-right-half-filled": Icons.StarRightHalfFilledIcon,
  "star-right-half-twotone": Icons.StarRightHalfTwotoneIcon,
  "star-twotone": Icons.StarTwotoneIcon,
  "star-twotone-half": Icons.StarTwotoneHalfIcon,
  "star-twotone-right-half": Icons.StarTwotoneRightHalfIcon,
  steering: Icons.SteeringIcon,
  "steering-off": Icons.SteeringOffIcon,
  "sun-rising": Icons.SunRisingIcon,
  "sun-rising-filled": Icons.SunRisingFilledIcon,
  "sun-rising-filled-loop": Icons.SunRisingFilledLoopIcon,
  "sun-rising-loop": Icons.SunRisingLoopIcon,
  "sun-rising-twotone": Icons.SunRisingTwotoneIcon,
  "sun-rising-twotone-loop": Icons.SunRisingTwotoneLoopIcon,
  sunny: Icons.SunnyIcon,
  "sunny-filled": Icons.SunnyFilledIcon,
  "sunny-filled-loop": Icons.SunnyFilledLoopIcon,
  "sunny-filled-loop-to-moon-filled-alt-loop-transition":
    Icons.SunnyFilledLoopToMoonFilledAltLoopTransitionIcon,
  "sunny-filled-loop-to-moon-filled-loop-transition":
    Icons.SunnyFilledLoopToMoonFilledLoopTransitionIcon,
  "sunny-filled-loop-to-moon-filled-transition":
    Icons.SunnyFilledLoopToMoonFilledTransitionIcon,
  "sunny-loop": Icons.SunnyLoopIcon,
  "sunny-off": Icons.SunnyOffIcon,
  "sunny-off-filled": Icons.SunnyOffFilledIcon,
  "sunny-off-filled-loop": Icons.SunnyOffFilledLoopIcon,
  "sunny-off-loop": Icons.SunnyOffLoopIcon,
  "sunny-off-twotone": Icons.SunnyOffTwotoneIcon,
  "sunny-off-twotone-loop": Icons.SunnyOffTwotoneLoopIcon,
  "sunny-outline-to-moon-alt-loop-transition":
    Icons.SunnyOutlineToMoonAltLoopTransitionIcon,
  "sunny-outline-to-moon-loop-transition":
    Icons.SunnyOutlineToMoonLoopTransitionIcon,
  "sunny-outline-to-moon-transition": Icons.SunnyOutlineToMoonTransitionIcon,
  "sunny-twotone": Icons.SunnyTwotoneIcon,
  "sunny-twotone-loop": Icons.SunnyTwotoneLoopIcon,
  switch: Icons.SwitchIcon,
  "switch-filled": Icons.SwitchFilledIcon,
  "switch-filled-to-switch-off-filled-transition":
    Icons.SwitchFilledToSwitchOffFilledTransitionIcon,
  "switch-off": Icons.SwitchOffIcon,
  "switch-off-filled": Icons.SwitchOffFilledIcon,
  "switch-off-filled-to-switch-filled-transition":
    Icons.SwitchOffFilledToSwitchFilledTransitionIcon,
  "switch-off-to-switch-transition": Icons.SwitchOffToSwitchTransitionIcon,
  "switch-off-twotone": Icons.SwitchOffTwotoneIcon,
  "switch-off-twotone-to-switch-twotone-transition":
    Icons.SwitchOffTwotoneToSwitchTwotoneTransitionIcon,
  "switch-to-switch-off-transition": Icons.SwitchToSwitchOffTransitionIcon,
  "switch-twotone": Icons.SwitchTwotoneIcon,
  "switch-twotone-to-switch-off-twotone-transition":
    Icons.SwitchTwotoneToSwitchOffTwotoneTransitionIcon,
  tablet: Icons.TabletIcon,
  "tablet-arrow-down": Icons.TabletArrowDownIcon,
  "tablet-arrow-down-twotone": Icons.TabletArrowDownTwotoneIcon,
  "tablet-arrow-up": Icons.TabletArrowUpIcon,
  "tablet-arrow-up-twotone": Icons.TabletArrowUpTwotoneIcon,
  "tablet-off": Icons.TabletOffIcon,
  "tablet-off-twotone": Icons.TabletOffTwotoneIcon,
  "tablet-screenshot": Icons.TabletScreenshotIcon,
  "tablet-screenshot-twotone": Icons.TabletScreenshotTwotoneIcon,
  "tablet-twotone": Icons.TabletTwotoneIcon,
  taco: Icons.TacoIcon,
  telegram: Icons.TelegramIcon,
  "text-box": Icons.TextBoxIcon,
  "text-box-multiple": Icons.TextBoxMultipleIcon,
  "text-box-multiple-to-text-box-transition":
    Icons.TextBoxMultipleToTextBoxTransitionIcon,
  "text-box-multiple-twotone": Icons.TextBoxMultipleTwotoneIcon,
  "text-box-multiple-twotone-to-text-box-twotone-transition":
    Icons.TextBoxMultipleTwotoneToTextBoxTwotoneTransitionIcon,
  "text-box-to-text-box-multiple-transition":
    Icons.TextBoxToTextBoxMultipleTransitionIcon,
  "text-box-twotone": Icons.TextBoxTwotoneIcon,
  "text-box-twotone-to-text-box-multiple-twotone-transition":
    Icons.TextBoxTwotoneToTextBoxMultipleTwotoneTransitionIcon,
  "thumbs-down": Icons.ThumbsDownIcon,
  "thumbs-down-filled": Icons.ThumbsDownFilledIcon,
  "thumbs-down-twotone": Icons.ThumbsDownTwotoneIcon,
  "thumbs-up": Icons.ThumbsUpIcon,
  "thumbs-up-filled": Icons.ThumbsUpFilledIcon,
  "thumbs-up-twotone": Icons.ThumbsUpTwotoneIcon,
  tiktok: Icons.TiktokIcon,
  trash: Icons.TrashIcon,
  "turn-left": Icons.TurnLeftIcon,
  "turn-right": Icons.TurnRightIcon,
  "turn-sharp-left": Icons.TurnSharpLeftIcon,
  "turn-sharp-right": Icons.TurnSharpRightIcon,
  "turn-slight-left": Icons.TurnSlightLeftIcon,
  "turn-slight-right": Icons.TurnSlightRightIcon,
  twitter: Icons.TwitterIcon,
  "twitter-filled": Icons.TwitterFilledIcon,
  "twitter-twotone": Icons.TwitterTwotoneIcon,
  "twitter-x": Icons.TwitterXIcon,
  "twitter-x-alt": Icons.TwitterXAltIcon,
  "u-turn-left": Icons.UTurnLeftIcon,
  "u-turn-right": Icons.UTurnRightIcon,
  upload: Icons.UploadIcon,
  "upload-loop": Icons.UploadLoopIcon,
  "upload-off": Icons.UploadOffIcon,
  "upload-off-loop": Icons.UploadOffLoopIcon,
  "upload-off-outline": Icons.UploadOffOutlineIcon,
  "upload-off-outline-loop": Icons.UploadOffOutlineLoopIcon,
  "upload-off-twotone": Icons.UploadOffTwotoneIcon,
  "upload-off-twotone-loop": Icons.UploadOffTwotoneLoopIcon,
  "upload-outline": Icons.UploadOutlineIcon,
  "upload-outline-loop": Icons.UploadOutlineLoopIcon,
  "upload-twotone": Icons.UploadTwotoneIcon,
  "upload-twotone-loop": Icons.UploadTwotoneLoopIcon,
  uploading: Icons.UploadingIcon,
  "uploading-loop": Icons.UploadingLoopIcon,
  "valign-baseline": Icons.ValignBaselineIcon,
  "valign-baseline-twotone": Icons.ValignBaselineTwotoneIcon,
  "valign-bottom": Icons.ValignBottomIcon,
  "valign-bottom-twotone": Icons.ValignBottomTwotoneIcon,
  "valign-middle": Icons.ValignMiddleIcon,
  "valign-middle-twotone": Icons.ValignMiddleTwotoneIcon,
  "valign-top": Icons.ValignTopIcon,
  "valign-top-twotone": Icons.ValignTopTwotoneIcon,
  "volume-high": Icons.VolumeHighIcon,
  "volume-high-filled": Icons.VolumeHighFilledIcon,
  "volume-high-off": Icons.VolumeHighOffIcon,
  "volume-high-off-filled": Icons.VolumeHighOffFilledIcon,
  "volume-high-off-twotone": Icons.VolumeHighOffTwotoneIcon,
  "volume-high-twotone": Icons.VolumeHighTwotoneIcon,
  "volume-low": Icons.VolumeLowIcon,
  "volume-low-filled": Icons.VolumeLowFilledIcon,
  "volume-low-off": Icons.VolumeLowOffIcon,
  "volume-low-off-filled": Icons.VolumeLowOffFilledIcon,
  "volume-low-off-twotone": Icons.VolumeLowOffTwotoneIcon,
  "volume-low-twotone": Icons.VolumeLowTwotoneIcon,
  "volume-medium": Icons.VolumeMediumIcon,
  "volume-medium-filled": Icons.VolumeMediumFilledIcon,
  "volume-medium-off": Icons.VolumeMediumOffIcon,
  "volume-medium-off-filled": Icons.VolumeMediumOffFilledIcon,
  "volume-medium-off-twotone": Icons.VolumeMediumOffTwotoneIcon,
  "volume-medium-twotone": Icons.VolumeMediumTwotoneIcon,
  "volume-minus": Icons.VolumeMinusIcon,
  "volume-minus-filled": Icons.VolumeMinusFilledIcon,
  "volume-minus-twotone": Icons.VolumeMinusTwotoneIcon,
  "volume-plus": Icons.VolumePlusIcon,
  "volume-plus-filled": Icons.VolumePlusFilledIcon,
  "volume-plus-twotone": Icons.VolumePlusTwotoneIcon,
  "volume-remove": Icons.VolumeRemoveIcon,
  "volume-remove-filled": Icons.VolumeRemoveFilledIcon,
  "volume-remove-twotone": Icons.VolumeRemoveTwotoneIcon,
  watch: Icons.WatchIcon,
  "watch-loop": Icons.WatchLoopIcon,
  "watch-off": Icons.WatchOffIcon,
  "watch-off-loop": Icons.WatchOffLoopIcon,
  "watch-off-twotone": Icons.WatchOffTwotoneIcon,
  "watch-off-twotone-loop": Icons.WatchOffTwotoneLoopIcon,
  "watch-twotone": Icons.WatchTwotoneIcon,
  "watch-twotone-loop": Icons.WatchTwotoneLoopIcon,
  water: Icons.WaterIcon,
  "water-filled": Icons.WaterFilledIcon,
  "water-off": Icons.WaterOffIcon,
  "water-off-filled": Icons.WaterOffFilledIcon,
  "water-off-twotone": Icons.WaterOffTwotoneIcon,
  "water-twotone": Icons.WaterTwotoneIcon,
  "weather-cloudy-loop": Icons.WeatherCloudyLoopIcon,
  youtube: Icons.YoutubeIcon,
  "youtube-filled": Icons.YoutubeFilledIcon,
  "youtube-twotone": Icons.YoutubeTwotoneIcon,
};
